// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "SystemArgumentDefinitions\AbilitySystemsArgs.h"
#include "ArgusLogging.h"

bool AbilitySystemsArgs::PopulateArguments(ArgusEntity entity)
{
	if (UNLIKELY(!entity))
	{
		return false;
	}

	m_entity = entity;
	m_abilityComponent = entity.GetComponent<AbilityComponent>();
	m_taskComponent = entity.GetComponent<TaskComponent>();
	m_targetingComponent = entity.GetComponent<TargetingComponent>();

	if (!m_entity || !m_abilityComponent || !m_taskComponent || !m_targetingComponent)
	{
		return false;
	}

	return true;
}

bool AbilitySystemsArgs::AreComponentsValidCheck(const WIDECHAR* functionName) const
{
	if (UNLIKELY(!m_entity || !m_abilityComponent || !m_taskComponent || !m_targetingComponent || !m_reticleComponent))
	{
		ArgusLogging::LogInvalidComponentReferences(functionName, ARGUS_NAMEOF(AbilitySystemsArgs));
		return false;
	}

	return true;
}
