// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "SystemArgumentDefinitions\FogOfWarSystemsArgs.h"
#include "ArgusLogging.h"

bool FogOfWarSystemsArgs::PopulateArguments(ArgusEntity entity)
{
	if (UNLIKELY(!entity))
	{
		return false;
	}

	m_entity = entity;
	m_fogOfWarLocationComponent = entity.GetComponent<FogOfWarLocationComponent>();
	m_targetingComponent = entity.GetComponent<TargetingComponent>();
	m_taskComponent = entity.GetComponent<TaskComponent>();
	m_transformComponent = entity.GetComponent<TransformComponent>();
	m_nearbyObstaclesComponent = entity.GetComponent<NearbyObstaclesComponent>();

	if (!m_entity || !m_fogOfWarLocationComponent || !m_targetingComponent || !m_taskComponent || !m_transformComponent)
	{
		return false;
	}

	return true;
}

bool FogOfWarSystemsArgs::AreComponentsValidCheck(const WIDECHAR* functionName) const
{
	if (UNLIKELY(!m_entity || !m_fogOfWarLocationComponent || !m_targetingComponent || !m_taskComponent || !m_transformComponent))
	{
		ArgusLogging::LogInvalidComponentReferences(functionName, ARGUS_NAMEOF(FogOfWarSystemsArgs));
		return false;
	}

	return true;
}
