// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "SystemArgumentDefinitions\FogOfWarSystemsArgs.h"
#include "ArgusLogging.h"

bool FogOfWarSystemsArgs::PopulateArguments(const ArgusEntity& entity)
{
	if (UNLIKELY(!entity))
	{
		return false;
	}

	m_entity = entity;
	m_targetingComponent = entity.GetComponent<TargetingComponent>();
	m_transformComponent = entity.GetComponent<TransformComponent>();

	if (!m_entity || !m_targetingComponent || !m_transformComponent)
	{
		return false;
	}

	return true;
}

bool FogOfWarSystemsArgs::AreComponentsValidCheck(const WIDECHAR* functionName) const
{
	if (UNLIKELY(!m_entity || !m_targetingComponent || !m_transformComponent))
	{
		ArgusLogging::LogInvalidComponentReferences(functionName, ARGUS_NAMEOF(FogOfWarSystemsArgs));
		return false;
	}

	return true;
}
