// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "SystemArgumentDefinitions\NavigationSystemsArgs.h"
#include "ArgusLogging.h"

bool NavigationSystemsArgs::PopulateArguments(ArgusEntity entity)
{
	if (UNLIKELY(!entity))
	{
		return false;
	}

	m_entity = entity;
	m_taskComponent = entity.GetComponent<TaskComponent>();
	m_navigationComponent = entity.GetComponent<NavigationComponent>();
	m_targetingComponent = entity.GetComponent<TargetingComponent>();
	m_transformComponent = entity.GetComponent<TransformComponent>();
	m_velocityComponent = entity.GetComponent<VelocityComponent>();
	m_avoidanceGroupingComponent = entity.GetComponent<AvoidanceGroupingComponent>();

	if (!m_entity || !m_taskComponent || !m_navigationComponent || !m_targetingComponent || !m_transformComponent || !m_velocityComponent)
	{
		return false;
	}

	return true;
}

bool NavigationSystemsArgs::AreComponentsValidCheck(const WIDECHAR* functionName) const
{
	if (UNLIKELY(!m_entity || !m_taskComponent || !m_navigationComponent || !m_targetingComponent || !m_transformComponent || !m_velocityComponent))
	{
		ArgusLogging::LogInvalidComponentReferences(functionName, ARGUS_NAMEOF(NavigationSystemsArgs));
		return false;
	}

	return true;
}
