// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "SystemArgumentDefinitions\TeamCommanderSystemsArgs.h"
#include "ArgusLogging.h"

bool TeamCommanderSystemsArgs::PopulateArguments(const ArgusEntity& entity)
{
	if (UNLIKELY(!entity))
	{
		return false;
	}

	m_entity = entity;
	m_taskComponent = entity.GetComponent<TaskComponent>();
	m_identityComponent = entity.GetComponent<IdentityComponent>();

	if (!m_entity || !m_taskComponent || !m_identityComponent)
	{
		return false;
	}

	return true;
}

bool TeamCommanderSystemsArgs::AreComponentsValidCheck(const WIDECHAR* functionName) const
{
	if (UNLIKELY(!m_entity || !m_taskComponent || !m_identityComponent))
	{
		ArgusLogging::LogInvalidComponentReferences(functionName, ARGUS_NAMEOF(TeamCommanderSystemsArgs));
		return false;
	}

	return true;
}
