// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "DynamicAllocComponentDefinitions/EffortCoefficientSettingsComponent.h"
#include "ArgusEntity.h"
#include "ArgusLogging.h"

#if !UE_BUILD_SHIPPING
#include "ArgusStaticData.h"
#include "imgui.h"
#include "UObject/ReflectedTypeAccessors.h"
#endif //!UE_BUILD_SHIPPING

// Component shared functionality
void EffortCoefficientSettingsComponent::Reset()
{
	m_sameAvoidanceGroupBase = 0.5f;
	m_sameAvoidanceGroupIsAttacking = 0.33f;
	m_sameAvoidanceGroupIsConstructing = 0.33f;
	m_sameTeamBothObstacle = 0.4f;
	m_sameTeamHasObstacle = 0.0f;
	m_sameTeamOtherHasObstacle = 1.0f;
}

void EffortCoefficientSettingsComponent::Serialize(FArchive& archive)
{
}

void EffortCoefficientSettingsComponent::DrawComponentDebug() const
{
#if !UE_BUILD_SHIPPING
	if (!ImGui::CollapsingHeader("EffortCoefficientSettingsComponent"))
	{
		return;
	}

	if (ImGui::BeginTable("ComponentValues", 2, ImGuiTableFlags_NoSavedSettings | ImGuiTableFlags_BordersInner))
	{
		ImGui::TableNextColumn();
		ImGui::Text("m_sameAvoidanceGroupBase");
		ImGui::TableNextColumn();
		ImGui::Text("%.2f", m_sameAvoidanceGroupBase);
		ImGui::TableNextColumn();
		ImGui::Text("m_sameAvoidanceGroupIsAttacking");
		ImGui::TableNextColumn();
		ImGui::Text("%.2f", m_sameAvoidanceGroupIsAttacking);
		ImGui::TableNextColumn();
		ImGui::Text("m_sameAvoidanceGroupIsConstructing");
		ImGui::TableNextColumn();
		ImGui::Text("%.2f", m_sameAvoidanceGroupIsConstructing);
		ImGui::TableNextColumn();
		ImGui::Text("m_sameTeamBothObstacle");
		ImGui::TableNextColumn();
		ImGui::Text("%.2f", m_sameTeamBothObstacle);
		ImGui::TableNextColumn();
		ImGui::Text("m_sameTeamHasObstacle");
		ImGui::TableNextColumn();
		ImGui::Text("%.2f", m_sameTeamHasObstacle);
		ImGui::TableNextColumn();
		ImGui::Text("m_sameTeamOtherHasObstacle");
		ImGui::TableNextColumn();
		ImGui::Text("%.2f", m_sameTeamOtherHasObstacle);
		ImGui::EndTable();
	}
#endif //!UE_BUILD_SHIPPING
}
