// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "DynamicAllocComponentDefinitions/MaterialCacheComponent.h"
#include "ArgusEntity.h"
#include "ArgusLogging.h"

#if !UE_BUILD_SHIPPING
#include "ArgusStaticData.h"
#include "imgui.h"
#include "UObject/ReflectedTypeAccessors.h"
#endif //!UE_BUILD_SHIPPING

// Component shared functionality
void MaterialCacheComponent::Reset()
{
}

void MaterialCacheComponent::DrawComponentDebug() const
{
#if !UE_BUILD_SHIPPING
	if (!ImGui::CollapsingHeader("MaterialCacheComponent"))
	{
		return;
	}

	if (ImGui::BeginTable("ComponentValues", 2, ImGuiTableFlags_NoSavedSettings))
	{
		ImGui::TableNextColumn();
		ImGui::Text("m_moveToLocationDecalMaterial");
		ImGui::TableNextColumn();
		ImGui::TableNextColumn();
		ImGui::Text("m_attackMoveToLocationDecalMaterial");
		ImGui::TableNextColumn();
		ImGui::EndTable();
	}
#endif //!UE_BUILD_SHIPPING
}
