// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "DynamicAllocComponentDefinitions/RelativePolygonComponent.h"
#include "ArgusEntity.h"
#include "ArgusLogging.h"

#if !UE_BUILD_SHIPPING
#include "ArgusStaticData.h"
#include "imgui.h"
#include "UObject/ReflectedTypeAccessors.h"
#endif //!UE_BUILD_SHIPPING

// Component shared functionality
void RelativePolygonComponent::Reset()
{
	m_relativeUnrealVerticies.Reset();
}

void RelativePolygonComponent::Serialize(FArchive& archive)
{
	archive << m_relativeUnrealVerticies;
}

void RelativePolygonComponent::DrawComponentDebug() const
{
#if !UE_BUILD_SHIPPING
	if (!ImGui::CollapsingHeader("RelativePolygonComponent"))
	{
		return;
	}

	if (ImGui::BeginTable("ComponentValues", 2, ImGuiTableFlags_NoSavedSettings | ImGuiTableFlags_BordersInner))
	{
		ImGui::TableNextColumn();
		ImGui::Text("m_relativeUnrealVerticies");
		ImGui::TableNextColumn();
		ImGui::Text("Array max is currently = %d", m_relativeUnrealVerticies.Max());
		if (m_relativeUnrealVerticies.IsEmpty())
		{
			ImGui::Text("Array is empty");
		}
		else
		{
			ImGui::Text("Size of array = %d", m_relativeUnrealVerticies.Num());
			ImGui::Indent();
			for (int32 i = 0; i < m_relativeUnrealVerticies.Num(); ++i)
			{
				if (i != 0) ImGui::Separator();
				ImGui::Text("(%.2f, %.2f)", m_relativeUnrealVerticies[i].X, m_relativeUnrealVerticies[i].Y);
			}
			ImGui::Unindent();
		}
		ImGui::EndTable();
	}
#endif //!UE_BUILD_SHIPPING
}
