// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "DynamicAllocComponentDefinitions/SpatialPartitioningComponent.h"
#include "ArgusEntity.h"
#include "ArgusLogging.h"

#if !UE_BUILD_SHIPPING
#include "ArgusStaticData.h"
#include "imgui.h"
#include "UObject/ReflectedTypeAccessors.h"
#endif //!UE_BUILD_SHIPPING

// Component shared functionality
void SpatialPartitioningComponent::Reset()
{
	m_argusEntityKDTree.FlushAllNodes();
	m_flyingArgusEntityKDTree.FlushAllNodes();
	m_obstaclePointKDTree.FlushAllNodes();
	m_worldCellExtent = 4000.0f;
	m_flyingPlaneHeight = 300.0f;
	m_elevatedObstaclePointHeightThreshold = 10.0f;
}

void SpatialPartitioningComponent::Serialize(FArchive& archive)
{
	archive << m_worldCellExtent;
	archive << m_flyingPlaneHeight;
	archive << m_elevatedObstaclePointHeightThreshold;
}

void SpatialPartitioningComponent::DrawComponentDebug() const
{
#if !UE_BUILD_SHIPPING
	if (!ImGui::CollapsingHeader("SpatialPartitioningComponent"))
	{
		return;
	}

	if (ImGui::BeginTable("ComponentValues", 2, ImGuiTableFlags_NoSavedSettings | ImGuiTableFlags_BordersInner))
	{
		ImGui::TableNextColumn();
		ImGui::Text("m_argusEntityKDTree");
		ImGui::TableNextColumn();
		ImGui::TableNextColumn();
		ImGui::Text("m_flyingArgusEntityKDTree");
		ImGui::TableNextColumn();
		ImGui::TableNextColumn();
		ImGui::Text("m_obstaclePointKDTree");
		ImGui::TableNextColumn();
		ImGui::TableNextColumn();
		ImGui::Text("m_initialWorldCell");
		ImGui::TableNextColumn();
		ImGui::TableNextColumn();
		ImGui::Text("m_worldCellExtent");
		ImGui::TableNextColumn();
		ImGui::Text("%.2f", m_worldCellExtent);
		ImGui::TableNextColumn();
		ImGui::Text("m_flyingPlaneHeight");
		ImGui::TableNextColumn();
		ImGui::Text("%.2f", m_flyingPlaneHeight);
		ImGui::TableNextColumn();
		ImGui::Text("m_elevatedObstaclePointHeightThreshold");
		ImGui::TableNextColumn();
		ImGui::Text("%.2f", m_elevatedObstaclePointHeightThreshold);
		ImGui::EndTable();
	}
#endif //!UE_BUILD_SHIPPING
}
