// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "DynamicAllocComponentDefinitions/TeamCommanderComponent.h"
#include "ArgusEntity.h"
#include "ArgusLogging.h"

#if !UE_BUILD_SHIPPING
#include "ArgusStaticData.h"
#include "imgui.h"
#include "UObject/ReflectedTypeAccessors.h"
#endif //!UE_BUILD_SHIPPING

// Component shared functionality
void TeamCommanderComponent::Reset()
{
	m_idleEntityIdsForTeam.Reset();
	m_seenResourceASourceEntityIds.Reset();
	m_seenResourceBSourceEntityIds.Reset();
	m_seenResourceCSourceEntityIds.Reset();
	m_resourceASinkEntityIds.Reset();
	m_resourceBSinkEntityIds.Reset();
	m_resourceCSinkEntityIds.Reset();
	m_priorities.Reset();
	m_revealedAreas.Reset();
	m_revealedAreaDimensionLength = 800.0f;
	m_teamToCommand = ETeam::None;
}

void TeamCommanderComponent::DrawComponentDebug() const
{
#if !UE_BUILD_SHIPPING
	if (!ImGui::CollapsingHeader("TeamCommanderComponent"))
	{
		return;
	}

	if (ImGui::BeginTable("ComponentValues", 2, ImGuiTableFlags_NoSavedSettings))
	{
		ImGui::TableNextColumn();
		ImGui::Text("m_idleEntityIdsForTeam");
		ImGui::TableNextColumn();
		ImGui::Text("Array max is currently = %d", m_idleEntityIdsForTeam.Max());
		if (m_idleEntityIdsForTeam.Num() == 0)
		{
			ImGui::Text("Array is empty");
		}
		else
		{
			ImGui::Text("Size of array = %d", m_idleEntityIdsForTeam.Num());
			ImGui::Indent();
			for (int32 i = 0; i < m_idleEntityIdsForTeam.Num(); ++i)
			{
				ImGui::Text("%d", m_idleEntityIdsForTeam[i]);
			}
			ImGui::Unindent();
		}
		ImGui::NewLine();
		ImGui::TableNextColumn();
		ImGui::Text("m_seenResourceASourceEntityIds");
		ImGui::TableNextColumn();
		ImGui::Text("Array max is currently = %d", m_seenResourceASourceEntityIds.Max());
		if (m_seenResourceASourceEntityIds.Num() == 0)
		{
			ImGui::Text("Array is empty");
		}
		else
		{
			ImGui::Text("Size of array = %d", m_seenResourceASourceEntityIds.Num());
			ImGui::Indent();
			for (int32 i = 0; i < m_seenResourceASourceEntityIds.Num(); ++i)
			{
				ImGui::Text("%d", m_seenResourceASourceEntityIds[i]);
			}
			ImGui::Unindent();
		}
		ImGui::NewLine();
		ImGui::TableNextColumn();
		ImGui::Text("m_seenResourceBSourceEntityIds");
		ImGui::TableNextColumn();
		ImGui::Text("Array max is currently = %d", m_seenResourceBSourceEntityIds.Max());
		if (m_seenResourceBSourceEntityIds.Num() == 0)
		{
			ImGui::Text("Array is empty");
		}
		else
		{
			ImGui::Text("Size of array = %d", m_seenResourceBSourceEntityIds.Num());
			ImGui::Indent();
			for (int32 i = 0; i < m_seenResourceBSourceEntityIds.Num(); ++i)
			{
				ImGui::Text("%d", m_seenResourceBSourceEntityIds[i]);
			}
			ImGui::Unindent();
		}
		ImGui::NewLine();
		ImGui::TableNextColumn();
		ImGui::Text("m_seenResourceCSourceEntityIds");
		ImGui::TableNextColumn();
		ImGui::Text("Array max is currently = %d", m_seenResourceCSourceEntityIds.Max());
		if (m_seenResourceCSourceEntityIds.Num() == 0)
		{
			ImGui::Text("Array is empty");
		}
		else
		{
			ImGui::Text("Size of array = %d", m_seenResourceCSourceEntityIds.Num());
			ImGui::Indent();
			for (int32 i = 0; i < m_seenResourceCSourceEntityIds.Num(); ++i)
			{
				ImGui::Text("%d", m_seenResourceCSourceEntityIds[i]);
			}
			ImGui::Unindent();
		}
		ImGui::NewLine();
		ImGui::TableNextColumn();
		ImGui::Text("m_resourceASinkEntityIds");
		ImGui::TableNextColumn();
		ImGui::Text("Array max is currently = %d", m_resourceASinkEntityIds.Max());
		if (m_resourceASinkEntityIds.Num() == 0)
		{
			ImGui::Text("Array is empty");
		}
		else
		{
			ImGui::Text("Size of array = %d", m_resourceASinkEntityIds.Num());
			ImGui::Indent();
			for (int32 i = 0; i < m_resourceASinkEntityIds.Num(); ++i)
			{
				ImGui::Text("%d", m_resourceASinkEntityIds[i]);
			}
			ImGui::Unindent();
		}
		ImGui::NewLine();
		ImGui::TableNextColumn();
		ImGui::Text("m_resourceBSinkEntityIds");
		ImGui::TableNextColumn();
		ImGui::Text("Array max is currently = %d", m_resourceBSinkEntityIds.Max());
		if (m_resourceBSinkEntityIds.Num() == 0)
		{
			ImGui::Text("Array is empty");
		}
		else
		{
			ImGui::Text("Size of array = %d", m_resourceBSinkEntityIds.Num());
			ImGui::Indent();
			for (int32 i = 0; i < m_resourceBSinkEntityIds.Num(); ++i)
			{
				ImGui::Text("%d", m_resourceBSinkEntityIds[i]);
			}
			ImGui::Unindent();
		}
		ImGui::NewLine();
		ImGui::TableNextColumn();
		ImGui::Text("m_resourceCSinkEntityIds");
		ImGui::TableNextColumn();
		ImGui::Text("Array max is currently = %d", m_resourceCSinkEntityIds.Max());
		if (m_resourceCSinkEntityIds.Num() == 0)
		{
			ImGui::Text("Array is empty");
		}
		else
		{
			ImGui::Text("Size of array = %d", m_resourceCSinkEntityIds.Num());
			ImGui::Indent();
			for (int32 i = 0; i < m_resourceCSinkEntityIds.Num(); ++i)
			{
				ImGui::Text("%d", m_resourceCSinkEntityIds[i]);
			}
			ImGui::Unindent();
		}
		ImGui::NewLine();
		ImGui::TableNextColumn();
		ImGui::Text("m_priorities");
		ImGui::TableNextColumn();
		ImGui::Text("Array max is currently = %d", m_priorities.Max());
		if (m_priorities.Num() == 0)
		{
			ImGui::Text("Array is empty");
		}
		else
		{
			ImGui::Text("Size of array = %d", m_priorities.Num());
			ImGui::Indent();
			for (int32 i = 0; i < m_priorities.Num(); ++i)
			{
				const char* valueName_m_priorities = ARGUS_FSTRING_TO_CHAR(StaticEnum<ETeamCommanderDirective>()->GetNameStringByValue(static_cast<uint8>(m_priorities[i].m_directive)))
				ImGui::Text(valueName_m_priorities);
				ImGui::Text("%.2f", m_priorities[i].m_weight);
			}
			ImGui::Unindent();
		}
		ImGui::NewLine();
		ImGui::TableNextColumn();
		ImGui::Text("m_revealedAreas");
		ImGui::TableNextColumn();
		ImGui::NewLine();
		ImGui::TableNextColumn();
		ImGui::Text("m_revealedAreaDimensionLength");
		ImGui::TableNextColumn();
		ImGui::Text("%.2f", m_revealedAreaDimensionLength);
		ImGui::NewLine();
		ImGui::TableNextColumn();
		ImGui::Text("m_teamToCommand");
		ImGui::TableNextColumn();
		const char* valueName_m_teamToCommand = ARGUS_FSTRING_TO_CHAR(StaticEnum<ETeam>()->GetNameStringByValue(static_cast<uint8>(m_teamToCommand)))
		ImGui::Text(valueName_m_teamToCommand);
		ImGui::NewLine();
		ImGui::EndTable();
	}
#endif //!UE_BUILD_SHIPPING
}
