// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ArgusMacros.h"
#include "RecordDefinitions\AbilityRecord.h"
#include "AbilityRecordDatabase.generated.h"

UCLASS()
class UAbilityRecordDatabase : public UDataAsset
{
	GENERATED_BODY()

public:
	const UAbilityRecord* GetRecord(uint32 id);
	void ResizePersistentObjectPointerArray();

protected:
	UPROPERTY(EditAnywhere)
	TArray<TSoftObjectPtr<UAbilityRecord>> m_UAbilityRecords;

	UPROPERTY(Transient)
	TArray<TObjectPtr<UAbilityRecord>> m_UAbilityRecordsPersistent;

public:
#if WITH_EDITOR && !IS_PACKAGING_ARGUS
	virtual void PreSave(FObjectPreSaveContext saveContext) override;
	virtual void PostEditChangeProperty(FPropertyChangedEvent& propertyChangedEvent) override;
	void AddUAbilityRecordToDatabase(UAbilityRecord* record);
#endif //WITH_EDITOR && !IS_PACKAGING_ARGUS
};
