// Copayright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "RecordDatabases/AbilityRecordDatabase.h"
#include "ArgusEntity.h"
#include "ArgusLogging.h"

#if WITH_EDITOR && !IS_PACKAGING_ARGUS
#include "ArgusStaticData.h"
#include "Editor.h"
#include "Misc/Paths.h"
#include "Subsystems/EditorAssetSubsystem.h"
#include "UObject/ObjectSaveContext.h"
#include <filesystem>
#endif //WITH_EDITOR && !IS_PACKAGING_ARGUS

const UAbilityRecord* UAbilityRecordDatabase::GetRecord(uint32 id)
{
	ARGUS_TRACE(UAbilityRecordDatabase::GetRecord)
	ARGUS_MEMORY_TRACE(ArgusStaticData);

	bool resized = false;
	if (static_cast<uint32>(m_UAbilityRecordsPersistent.Num()) <= id)
	{
		if (!ResizePersistentObjectPointerArrayToFitRecord(id))
		{
			return nullptr;
		}		
		resized = true;
	}

	if (id == 0u)
	{
		return nullptr;
	}

	if (resized || !m_UAbilityRecordsPersistent[id])
	{
		m_UAbilityRecordsPersistent[id] = m_UAbilityRecords[id].LoadSynchronous();
	}

	if (m_UAbilityRecordsPersistent[id])
	{
		m_UAbilityRecordsPersistent[id]->m_id = id;
	}

	return m_UAbilityRecordsPersistent[id];
}

const bool UAbilityRecordDatabase::PreLoadRecord(uint32 id)
{
	ARGUS_TRACE(UAbilityRecordDatabase::PreLoadRecord);
	ARGUS_MEMORY_TRACE(ArgusStaticData);

	if (static_cast<uint32>(m_UAbilityRecordsPersistent.Num()) <= id)
	{
		if (!ResizePersistentObjectPointerArrayToFitRecord(id))
		{
			return false;
		}
	}

	if (m_UAbilityRecordsPersistent[id])
	{
		return true;
	}

	AssetLoadingComponent* assetLoadingComponent = ArgusEntity::GetSingletonEntity().GetComponent<AssetLoadingComponent>();
	ARGUS_RETURN_ON_NULL_BOOL(assetLoadingComponent, ArgusStaticDataLog);

	assetLoadingComponent->m_streamableManager.RequestAsyncLoad(m_UAbilityRecords[id].ToSoftObjectPath(), FStreamableDelegate::CreateLambda
	(
		[this, id]()
		{
			if (static_cast<uint32>(m_UAbilityRecordsPersistent.Num()) <= id || static_cast<uint32>(m_UAbilityRecords.Num()) <= id)
			{
				return;
			}

			m_UAbilityRecordsPersistent[id] = m_UAbilityRecords[id].Get();
		})
	);

	return true;
}

bool UAbilityRecordDatabase::ResizePersistentObjectPointerArrayToFitRecord(uint32 id)
{
	ARGUS_MEMORY_TRACE(ArgusStaticData);

	m_UAbilityRecordsPersistent.SetNumZeroed(m_UAbilityRecords.Num());
	if (static_cast<uint32>(m_UAbilityRecordsPersistent.Num()) <= id)
	{
		ARGUS_LOG
		(
			ArgusStaticDataLog, Error,
			TEXT("[%s] Could not find %s %d in %s."),
			ARGUS_FUNCNAME,
			ARGUS_NAMEOF(id),
			id,
			ARGUS_NAMEOF(UAbilityRecordDatabase)
		);

		return false;
	}

	return true;
}

#if WITH_EDITOR && !IS_PACKAGING_ARGUS
void UAbilityRecordDatabase::PreSave(FObjectPreSaveContext saveContext)
{
	FString fullPath = FPaths::ConvertRelativePathToFull(saveContext.GetTargetFilename());
	if (!std::filesystem::exists(TCHAR_TO_UTF8(*fullPath)))
	{
		TArray<FReferencerInformation> internalReferencers;
		TArray<FReferencerInformation> externalReferencers;
		RetrieveReferencers(&internalReferencers, &externalReferencers);

		if (internalReferencers.IsEmpty() && externalReferencers.IsEmpty())
		{
			ArgusStaticData::RegisterNewUAbilityRecordDatabase(this);
		}
	}

	Super::PreSave(saveContext);
}

void UAbilityRecordDatabase::PostEditChangeProperty(FPropertyChangedEvent& propertyChangedEvent)
{
	if (propertyChangedEvent.ChangeType != EPropertyChangeType::ValueSet)
	{
		return;
	}

	const FString propertyName = propertyChangedEvent.GetPropertyName().ToString();
	const FString recordPropertyName = ARGUS_NAMEOF(m_UAbilityRecords);
	if (!propertyName.Equals(recordPropertyName))
	{
		return;
	}

	const int32 arrayIndex = propertyChangedEvent.GetArrayIndex(propertyName);
	UAbilityRecord* modifiedUAbilityRecord = m_UAbilityRecords[arrayIndex].LoadSynchronous();
	if (!modifiedUAbilityRecord)
	{
		return;
	}

	modifiedUAbilityRecord->m_id = arrayIndex;

	if (!GEditor)
	{
		return;
	}

	UEditorAssetSubsystem* editorAssetSubsystem = GEditor->GetEditorSubsystem<UEditorAssetSubsystem>();
	if (!editorAssetSubsystem)
	{
		return;
	}

	editorAssetSubsystem->SaveLoadedAsset(modifiedUAbilityRecord, false);
	editorAssetSubsystem->SaveLoadedAsset(this, false);
}

void UAbilityRecordDatabase::AddUAbilityRecordToDatabase(UAbilityRecord* record)
{
	const int32 arrayIndex = m_UAbilityRecords.Num();
	m_UAbilityRecords.Add(TSoftObjectPtr(record));

	record->m_id = arrayIndex;

	if (!GEditor)
	{
		return;
	}

	UEditorAssetSubsystem* editorAssetSubsystem = GEditor->GetEditorSubsystem<UEditorAssetSubsystem>();
	if (!editorAssetSubsystem)
	{
		return;
	}

	editorAssetSubsystem->SaveLoadedAsset(this, false);
}
#endif //WITH_EDITOR && !IS_PACKAGING_ARGUS
