// Copayright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "RecordDatabases/FactionRecordDatabase.h"
#include "ArgusEntity.h"
#include "ArgusLogging.h"

#if WITH_EDITOR && !IS_PACKAGING_ARGUS
#include "ArgusStaticData.h"
#include "Editor.h"
#include "Misc/Paths.h"
#include "Subsystems/EditorAssetSubsystem.h"
#include "UObject/ObjectSaveContext.h"
#include <filesystem>
#endif //WITH_EDITOR && !IS_PACKAGING_ARGUS

const UFactionRecord* UFactionRecordDatabase::GetRecord(uint32 id)
{
	ARGUS_TRACE(UFactionRecordDatabase::GetRecord)
	ARGUS_MEMORY_TRACE(ArgusStaticData);

	bool resized = false;
	if (static_cast<uint32>(m_UFactionRecordsPersistent.Num()) <= id)
	{
		if (!ResizePersistentObjectPointerArrayToFitRecord(id))
		{
			return nullptr;
		}		
		resized = true;
	}

	if (id == 0u)
	{
		return nullptr;
	}

	if (resized || !m_UFactionRecordsPersistent[id])
	{
		m_UFactionRecordsPersistent[id] = m_UFactionRecords[id].LoadSynchronous();
	}

	if (m_UFactionRecordsPersistent[id])
	{
		m_UFactionRecordsPersistent[id]->m_id = id;
	}

	return m_UFactionRecordsPersistent[id];
}

const bool UFactionRecordDatabase::AsyncPreLoadRecord(uint32 id)
{
	ARGUS_TRACE(UFactionRecordDatabase::AsyncPreLoadRecord);
	ARGUS_MEMORY_TRACE(ArgusStaticData);

	if (static_cast<uint32>(m_UFactionRecordsPersistent.Num()) <= id)
	{
		if (!ResizePersistentObjectPointerArrayToFitRecord(id))
		{
			return false;
		}
	}

	if (m_UFactionRecordsPersistent[id])
	{
		return true;
	}

	AssetLoadingComponent* assetLoadingComponent = ArgusEntity::GetSingletonEntity().GetComponent<AssetLoadingComponent>();
	ARGUS_RETURN_ON_NULL_BOOL(assetLoadingComponent, ArgusStaticDataLog);

	assetLoadingComponent->m_streamableManager.RequestAsyncLoad(m_UFactionRecords[id].ToSoftObjectPath(), FStreamableDelegate::CreateLambda
	(
		[this, id]()
		{
			if (static_cast<uint32>(m_UFactionRecordsPersistent.Num()) <= id || static_cast<uint32>(m_UFactionRecords.Num()) <= id)
			{
				return;
			}

			m_UFactionRecordsPersistent[id] = m_UFactionRecords[id].Get();\
			if (m_UFactionRecordsPersistent[id])
			{
				m_UFactionRecordsPersistent[id]->OnAsyncLoaded();
			}
		})
	);

	return true;
}

bool UFactionRecordDatabase::ResizePersistentObjectPointerArrayToFitRecord(uint32 id)
{
	ARGUS_MEMORY_TRACE(ArgusStaticData);

	m_UFactionRecordsPersistent.SetNumZeroed(m_UFactionRecords.Num());
	if (static_cast<uint32>(m_UFactionRecordsPersistent.Num()) <= id)
	{
		ARGUS_LOG
		(
			ArgusStaticDataLog, Error,
			TEXT("[%s] Could not find %s %d in %s."),
			ARGUS_FUNCNAME,
			ARGUS_NAMEOF(id),
			id,
			ARGUS_NAMEOF(UFactionRecordDatabase)
		);

		return false;
	}

	return true;
}

#if WITH_EDITOR && !IS_PACKAGING_ARGUS
void UFactionRecordDatabase::PreSave(FObjectPreSaveContext saveContext)
{
	FString fullPath = FPaths::ConvertRelativePathToFull(saveContext.GetTargetFilename());
	if (!std::filesystem::exists(TCHAR_TO_UTF8(*fullPath)))
	{
		TArray<FReferencerInformation> internalReferencers;
		TArray<FReferencerInformation> externalReferencers;
		RetrieveReferencers(&internalReferencers, &externalReferencers);

		if (internalReferencers.IsEmpty() && externalReferencers.IsEmpty())
		{
			ArgusStaticData::RegisterNewUFactionRecordDatabase(this);
		}
	}

	Super::PreSave(saveContext);
}

void UFactionRecordDatabase::PostEditChangeProperty(FPropertyChangedEvent& propertyChangedEvent)
{
	if (propertyChangedEvent.ChangeType != EPropertyChangeType::ValueSet)
	{
		return;
	}

	const FString propertyName = propertyChangedEvent.GetPropertyName().ToString();
	const FString recordPropertyName = ARGUS_NAMEOF(m_UFactionRecords);
	if (!propertyName.Equals(recordPropertyName))
	{
		return;
	}

	const int32 arrayIndex = propertyChangedEvent.GetArrayIndex(propertyName);
	UFactionRecord* modifiedUFactionRecord = m_UFactionRecords[arrayIndex].LoadSynchronous();
	if (!modifiedUFactionRecord)
	{
		return;
	}

	modifiedUFactionRecord->m_id = arrayIndex;

	if (!GEditor)
	{
		return;
	}

	UEditorAssetSubsystem* editorAssetSubsystem = GEditor->GetEditorSubsystem<UEditorAssetSubsystem>();
	if (!editorAssetSubsystem)
	{
		return;
	}

	editorAssetSubsystem->SaveLoadedAsset(modifiedUFactionRecord, false);
	editorAssetSubsystem->SaveLoadedAsset(this, false);
}

void UFactionRecordDatabase::AddUFactionRecordToDatabase(UFactionRecord* record)
{
	const int32 arrayIndex = m_UFactionRecords.Num();
	m_UFactionRecords.Add(TSoftObjectPtr(record));

	record->m_id = arrayIndex;

	if (!GEditor)
	{
		return;
	}

	UEditorAssetSubsystem* editorAssetSubsystem = GEditor->GetEditorSubsystem<UEditorAssetSubsystem>();
	if (!editorAssetSubsystem)
	{
		return;
	}

	editorAssetSubsystem->SaveLoadedAsset(this, false);
}
#endif //WITH_EDITOR && !IS_PACKAGING_ARGUS
