// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "RecordDatabases/MaterialRecordDatabase.h"
#include "ArgusEntity.h"
#include "ArgusLogging.h"

#if WITH_EDITOR
#include "ArgusStaticData.h"
#include "Editor.h"
#include "Misc/Paths.h"
#include "Subsystems/EditorAssetSubsystem.h"
#include "UObject/ObjectSaveContext.h"
#include <filesystem>
#endif //WITH_EDITOR

const UMaterialRecord* UMaterialRecordDatabase::GetRecord(uint32 id)
{
	ARGUS_TRACE(UMaterialRecordDatabase::GetRecord)
	ARGUS_MEMORY_TRACE(ArgusStaticData);

	if (id == 0u)
	{
		return nullptr;
	}

	bool resized = false;
	if (static_cast<uint32>(m_UMaterialRecordsPersistent.Num()) <= id)
	{
		if (!ResizePersistentObjectPointerArrayToFitRecord(id))
		{
			return nullptr;
		}		
		resized = true;
	}

	if (resized || !m_UMaterialRecordsPersistent[id])
	{
		m_UMaterialRecordsPersistent[id] = m_UMaterialRecords[id].LoadSynchronous();
		if (m_UMaterialRecordsPersistent[id])
		{
			m_UMaterialRecordsPersistent[id]->OnAsyncLoaded();
			m_UMaterialRecordsPersistent[id]->m_id = id;
		}
	}

	return m_UMaterialRecordsPersistent[id];
}

const bool UMaterialRecordDatabase::AsyncPreLoadRecord(uint32 id, TFunction<void(const UMaterialRecord*)> callback)
{
	ARGUS_TRACE(UMaterialRecordDatabase::AsyncPreLoadRecord);
	ARGUS_MEMORY_TRACE(ArgusStaticData);

	if (static_cast<uint32>(m_UMaterialRecordsPersistent.Num()) <= id)
	{
		if (!ResizePersistentObjectPointerArrayToFitRecord(id))
		{
			return false;
		}
	}

	if (id == 0u)
	{
		return false;
	}

	if (m_UMaterialRecordsPersistent[id])
	{
		return true;
	}

	AssetLoadingComponent* assetLoadingComponent = ArgusEntity::GetSingletonEntity().GetComponent<AssetLoadingComponent>();
	ARGUS_RETURN_ON_NULL_BOOL(assetLoadingComponent, ArgusStaticDataLog);

	assetLoadingComponent->m_streamableManager.RequestAsyncLoad(m_UMaterialRecords[id].ToSoftObjectPath(), FStreamableDelegate::CreateLambda
	(
		[this, id, callback]()
		{
			if (static_cast<uint32>(m_UMaterialRecordsPersistent.Num()) <= id || static_cast<uint32>(m_UMaterialRecords.Num()) <= id)
			{
				return;
			}

			m_UMaterialRecordsPersistent[id] = m_UMaterialRecords[id].Get();
			if (m_UMaterialRecordsPersistent[id])
			{
				m_UMaterialRecordsPersistent[id]->OnAsyncLoaded();
				m_UMaterialRecordsPersistent[id]->m_id = id;
				if (callback)
				{
					callback(m_UMaterialRecordsPersistent[id]);
				}
			}
		})
	);

	return true;
}

bool UMaterialRecordDatabase::ResizePersistentObjectPointerArrayToFitRecord(uint32 id)
{
	ARGUS_MEMORY_TRACE(ArgusStaticData);

	m_UMaterialRecordsPersistent.SetNumZeroed(m_UMaterialRecords.Num());
	if (static_cast<uint32>(m_UMaterialRecordsPersistent.Num()) <= id)
	{
		ARGUS_LOG
		(
			ArgusStaticDataLog, Error,
			TEXT("[%s] Could not find %s %d in %s."),
			ARGUS_FUNCNAME,
			ARGUS_NAMEOF(id),
			id,
			ARGUS_NAMEOF(UMaterialRecordDatabase)
		);

		return false;
	}

	return true;
}

void UMaterialRecordDatabase::ResetPersistentObjectPointerArray()
{
	m_UMaterialRecordsPersistent.Reset();
}

#if WITH_EDITOR
void UMaterialRecordDatabase::PreSave(FObjectPreSaveContext saveContext)
{
	Super::PreSave(saveContext);
	if (saveContext.IsCooking() || saveContext.GetTargetPlatform())
	{
		return;
	}

	FString fullPath = FPaths::ConvertRelativePathToFull(saveContext.GetTargetFilename());
	if (!std::filesystem::exists(TCHAR_TO_UTF8(*fullPath)))
	{
		TArray<FReferencerInformation> internalReferencers;
		TArray<FReferencerInformation> externalReferencers;
		RetrieveReferencers(&internalReferencers, &externalReferencers);

		if (internalReferencers.IsEmpty() && externalReferencers.IsEmpty())
		{
			ArgusStaticData::RegisterNewUMaterialRecordDatabase(this);
		}
	}

	Super::PreSave(saveContext);
}

void UMaterialRecordDatabase::PostEditChangeProperty(FPropertyChangedEvent& propertyChangedEvent)
{
	if (propertyChangedEvent.ChangeType != EPropertyChangeType::ValueSet)
	{
		return;
	}

	const FString propertyName = propertyChangedEvent.GetPropertyName().ToString();
	const FString recordPropertyName = ARGUS_NAMEOF(m_UMaterialRecords);
	if (!propertyName.Equals(recordPropertyName))
	{
		return;
	}

	const int32 arrayIndex = propertyChangedEvent.GetArrayIndex(propertyName);
	UMaterialRecord* modifiedUMaterialRecord = m_UMaterialRecords[arrayIndex].LoadSynchronous();
	if (!modifiedUMaterialRecord)
	{
		return;
	}

	modifiedUMaterialRecord->m_id = arrayIndex;

	if (!GEditor)
	{
		return;
	}

	UEditorAssetSubsystem* editorAssetSubsystem = GEditor->GetEditorSubsystem<UEditorAssetSubsystem>();
	if (!editorAssetSubsystem)
	{
		return;
	}

	editorAssetSubsystem->SaveLoadedAsset(modifiedUMaterialRecord, false);
	editorAssetSubsystem->SaveLoadedAsset(this, false);
}

void UMaterialRecordDatabase::AddUMaterialRecordToDatabase(UMaterialRecord* record)
{
	const int32 arrayIndex = m_UMaterialRecords.Num();
	m_UMaterialRecords.Add(TSoftObjectPtr(record));

	record->m_id = arrayIndex;

	if (!GEditor)
	{
		return;
	}

	UEditorAssetSubsystem* editorAssetSubsystem = GEditor->GetEditorSubsystem<UEditorAssetSubsystem>();
	if (!editorAssetSubsystem)
	{
		return;
	}

	editorAssetSubsystem->SaveLoadedAsset(this, false);
}
#endif //WITH_EDITOR
