// Copayright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "RecordDatabases/PlacedArgusActorTeamInfoRecordDatabase.h"
#include "ArgusEntity.h"
#include "ArgusLogging.h"

#if WITH_EDITOR && !IS_PACKAGING_ARGUS
#include "ArgusStaticData.h"
#include "Editor.h"
#include "Misc/Paths.h"
#include "Subsystems/EditorAssetSubsystem.h"
#include "UObject/ObjectSaveContext.h"
#include <filesystem>
#endif //WITH_EDITOR && !IS_PACKAGING_ARGUS

const UPlacedArgusActorTeamInfoRecord* UPlacedArgusActorTeamInfoRecordDatabase::GetRecord(uint32 id)
{
	ARGUS_TRACE(UPlacedArgusActorTeamInfoRecordDatabase::GetRecord)
	ARGUS_MEMORY_TRACE(ArgusStaticData);

	bool resized = false;
	if (static_cast<uint32>(m_UPlacedArgusActorTeamInfoRecordsPersistent.Num()) <= id)
	{
		if (!ResizePersistentObjectPointerArrayToFitRecord(id))
		{
			return nullptr;
		}		
		resized = true;
	}

	if (id == 0u)
	{
		return nullptr;
	}

	if (resized || !m_UPlacedArgusActorTeamInfoRecordsPersistent[id])
	{
		m_UPlacedArgusActorTeamInfoRecordsPersistent[id] = m_UPlacedArgusActorTeamInfoRecords[id].LoadSynchronous();
	}

	if (m_UPlacedArgusActorTeamInfoRecordsPersistent[id])
	{
		m_UPlacedArgusActorTeamInfoRecordsPersistent[id]->m_id = id;
	}

	return m_UPlacedArgusActorTeamInfoRecordsPersistent[id];
}

const bool UPlacedArgusActorTeamInfoRecordDatabase::AsyncPreLoadRecord(uint32 id)
{
	ARGUS_TRACE(UPlacedArgusActorTeamInfoRecordDatabase::AsyncPreLoadRecord);
	ARGUS_MEMORY_TRACE(ArgusStaticData);

	if (static_cast<uint32>(m_UPlacedArgusActorTeamInfoRecordsPersistent.Num()) <= id)
	{
		if (!ResizePersistentObjectPointerArrayToFitRecord(id))
		{
			return false;
		}
	}

	if (id == 0u)
	{
		return false;
	}

	if (m_UPlacedArgusActorTeamInfoRecordsPersistent[id])
	{
		return true;
	}

	AssetLoadingComponent* assetLoadingComponent = ArgusEntity::GetSingletonEntity().GetComponent<AssetLoadingComponent>();
	ARGUS_RETURN_ON_NULL_BOOL(assetLoadingComponent, ArgusStaticDataLog);

	assetLoadingComponent->m_streamableManager.RequestAsyncLoad(m_UPlacedArgusActorTeamInfoRecords[id].ToSoftObjectPath(), FStreamableDelegate::CreateLambda
	(
		[this, id]()
		{
			if (static_cast<uint32>(m_UPlacedArgusActorTeamInfoRecordsPersistent.Num()) <= id || static_cast<uint32>(m_UPlacedArgusActorTeamInfoRecords.Num()) <= id)
			{
				return;
			}

			m_UPlacedArgusActorTeamInfoRecordsPersistent[id] = m_UPlacedArgusActorTeamInfoRecords[id].Get();\
			if (m_UPlacedArgusActorTeamInfoRecordsPersistent[id])
			{
				m_UPlacedArgusActorTeamInfoRecordsPersistent[id]->OnAsyncLoaded();
			}
		})
	);

	return true;
}

bool UPlacedArgusActorTeamInfoRecordDatabase::ResizePersistentObjectPointerArrayToFitRecord(uint32 id)
{
	ARGUS_MEMORY_TRACE(ArgusStaticData);

	m_UPlacedArgusActorTeamInfoRecordsPersistent.SetNumZeroed(m_UPlacedArgusActorTeamInfoRecords.Num());
	if (static_cast<uint32>(m_UPlacedArgusActorTeamInfoRecordsPersistent.Num()) <= id)
	{
		ARGUS_LOG
		(
			ArgusStaticDataLog, Error,
			TEXT("[%s] Could not find %s %d in %s."),
			ARGUS_FUNCNAME,
			ARGUS_NAMEOF(id),
			id,
			ARGUS_NAMEOF(UPlacedArgusActorTeamInfoRecordDatabase)
		);

		return false;
	}

	return true;
}

#if WITH_EDITOR && !IS_PACKAGING_ARGUS
void UPlacedArgusActorTeamInfoRecordDatabase::PreSave(FObjectPreSaveContext saveContext)
{
	FString fullPath = FPaths::ConvertRelativePathToFull(saveContext.GetTargetFilename());
	if (!std::filesystem::exists(TCHAR_TO_UTF8(*fullPath)))
	{
		TArray<FReferencerInformation> internalReferencers;
		TArray<FReferencerInformation> externalReferencers;
		RetrieveReferencers(&internalReferencers, &externalReferencers);

		if (internalReferencers.IsEmpty() && externalReferencers.IsEmpty())
		{
			ArgusStaticData::RegisterNewUPlacedArgusActorTeamInfoRecordDatabase(this);
		}
	}

	Super::PreSave(saveContext);
}

void UPlacedArgusActorTeamInfoRecordDatabase::PostEditChangeProperty(FPropertyChangedEvent& propertyChangedEvent)
{
	if (propertyChangedEvent.ChangeType != EPropertyChangeType::ValueSet)
	{
		return;
	}

	const FString propertyName = propertyChangedEvent.GetPropertyName().ToString();
	const FString recordPropertyName = ARGUS_NAMEOF(m_UPlacedArgusActorTeamInfoRecords);
	if (!propertyName.Equals(recordPropertyName))
	{
		return;
	}

	const int32 arrayIndex = propertyChangedEvent.GetArrayIndex(propertyName);
	UPlacedArgusActorTeamInfoRecord* modifiedUPlacedArgusActorTeamInfoRecord = m_UPlacedArgusActorTeamInfoRecords[arrayIndex].LoadSynchronous();
	if (!modifiedUPlacedArgusActorTeamInfoRecord)
	{
		return;
	}

	modifiedUPlacedArgusActorTeamInfoRecord->m_id = arrayIndex;

	if (!GEditor)
	{
		return;
	}

	UEditorAssetSubsystem* editorAssetSubsystem = GEditor->GetEditorSubsystem<UEditorAssetSubsystem>();
	if (!editorAssetSubsystem)
	{
		return;
	}

	editorAssetSubsystem->SaveLoadedAsset(modifiedUPlacedArgusActorTeamInfoRecord, false);
	editorAssetSubsystem->SaveLoadedAsset(this, false);
}

void UPlacedArgusActorTeamInfoRecordDatabase::AddUPlacedArgusActorTeamInfoRecordToDatabase(UPlacedArgusActorTeamInfoRecord* record)
{
	const int32 arrayIndex = m_UPlacedArgusActorTeamInfoRecords.Num();
	m_UPlacedArgusActorTeamInfoRecords.Add(TSoftObjectPtr(record));

	record->m_id = arrayIndex;

	if (!GEditor)
	{
		return;
	}

	UEditorAssetSubsystem* editorAssetSubsystem = GEditor->GetEditorSubsystem<UEditorAssetSubsystem>();
	if (!editorAssetSubsystem)
	{
		return;
	}

	editorAssetSubsystem->SaveLoadedAsset(this, false);
}
#endif //WITH_EDITOR && !IS_PACKAGING_ARGUS
