// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "RecordDefinitions\ResourceSetRecord.h"
#include "ResourceSetRecordDatabase.generated.h"

UCLASS()
class UResourceSetRecordDatabase : public UDataAsset
{
	GENERATED_BODY()

public:
	const UResourceSetRecord* GetRecord(uint32 id);
	void ResizePersistentObjectPointerArray();

protected:
	UPROPERTY(EditAnywhere)
	TArray<TSoftObjectPtr<UResourceSetRecord>> m_UResourceSetRecords;

	UPROPERTY(Transient)
	TArray<TObjectPtr<UResourceSetRecord>> m_UResourceSetRecordsPersistent;

public:
#if WITH_EDITOR
	virtual void PreSave(FObjectPreSaveContext saveContext) override;
	virtual void PostEditChangeProperty(FPropertyChangedEvent& propertyChangedEvent) override;
	void AddUResourceSetRecordToDatabase(UResourceSetRecord* record);
#endif //WITH_EDITOR
};
