// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ArgusMacros.h"
#include "RecordDefinitions/WorldCellRecord.h"
#include "WorldCellRecordDatabase.generated.h"

UCLASS()
class UWorldCellRecordDatabase : public UDataAsset
{
	GENERATED_BODY()

public:
	const UWorldCellRecord* GetRecord(uint32 id);
	const bool AsyncPreLoadRecord(uint32 id, TFunction<void(const UWorldCellRecord*)> callback = nullptr);
	bool ResizePersistentObjectPointerArrayToFitRecord(uint32 id);
	void ResetPersistentObjectPointerArray();

protected:
	UPROPERTY(EditAnywhere)
	TArray<TSoftObjectPtr<UWorldCellRecord>> m_UWorldCellRecords;

	UPROPERTY(Transient)
	TArray<TObjectPtr<UWorldCellRecord>> m_UWorldCellRecordsPersistent;

public:
#if WITH_EDITOR
	virtual void PreSave(FObjectPreSaveContext saveContext) override;
	virtual void PostEditChangeProperty(FPropertyChangedEvent& propertyChangedEvent) override;
	void AddUWorldCellRecordToDatabase(UWorldCellRecord* record);
	void IterateAllUWorldCellRecords(const TFunctionRef<void(UWorldCellRecord*)>& function);
#endif //WITH_EDITOR
};
