// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ArgusLogging.h"
#include "ArgusStaticDatabase.h"

class UArgusStaticRecord;

class ArgusStaticData
{
public:
	static void ResetLoadedPointerArrays() 
	{		
		if (UArgusStaticDatabase* staticDatabase = UArgusStaticDatabase::GetInstance())
		{
			staticDatabase->ResetLoadedPointerArrays();
		}		
	}

	template<typename ArgusStaticRecord>
	static const ArgusStaticRecord* GetRecord(uint32 id)
	{
		return nullptr;
	}

	template<typename ArgusStaticRecord>
	static bool AsyncPreLoadRecord(uint32 id, TFunction<void(const ArgusStaticRecord*)> callback = nullptr)
	{
		return false;
	}

#if WITH_EDITOR
	template<typename ArgusStaticRecord>
	static void IterateAllRecordsOfType(const TFunctionRef<void(ArgusStaticRecord*)>& function)
	{
	}

	static uint32 AddRecordToDatabase(UArgusStaticRecord* record);
#endif //WITH_EDITOR

#pragma region UAbilityRecord
	template<>
	ARGUS_API inline const UAbilityRecord* GetRecord(uint32 id)
	{
		if (UArgusStaticDatabase* staticDatabase = UArgusStaticDatabase::GetInstance())
		{
			return staticDatabase->GetUAbilityRecord(id);
		}

		return nullptr;
	}

	template<>
	ARGUS_API inline bool AsyncPreLoadRecord<UAbilityRecord>(uint32 id, TFunction<void(const UAbilityRecord*)> callback)
	{
		if (UArgusStaticDatabase* staticDatabase = UArgusStaticDatabase::GetInstance())
		{
			return staticDatabase->AsyncPreLoadUAbilityRecord(id, callback);
		}

		return false;
	}

#if WITH_EDITOR
	template<>
	ARGUS_API inline void IterateAllRecordsOfType<UAbilityRecord>(const TFunctionRef<void(UAbilityRecord*)>& function)
	{
		if (UArgusStaticDatabase* staticDatabase = GetParentDatabase())
		{
			staticDatabase->IterateAllUAbilityRecords(function);
		}
	}

	static void RegisterNewUAbilityRecordDatabase(UAbilityRecordDatabase* database)
	{
		UArgusStaticDatabase* staticDatabase = GetParentDatabase();
		ARGUS_RETURN_ON_NULL(staticDatabase, ArgusStaticDataLog);
		staticDatabase->RegisterNewUAbilityRecordDatabase(database);
	}
#endif //WITH_EDITOR
#pragma endregion

#pragma region UArgusActorRecord
	template<>
	ARGUS_API inline const UArgusActorRecord* GetRecord(uint32 id)
	{
		if (UArgusStaticDatabase* staticDatabase = UArgusStaticDatabase::GetInstance())
		{
			return staticDatabase->GetUArgusActorRecord(id);
		}

		return nullptr;
	}

	template<>
	ARGUS_API inline bool AsyncPreLoadRecord<UArgusActorRecord>(uint32 id, TFunction<void(const UArgusActorRecord*)> callback)
	{
		if (UArgusStaticDatabase* staticDatabase = UArgusStaticDatabase::GetInstance())
		{
			return staticDatabase->AsyncPreLoadUArgusActorRecord(id, callback);
		}

		return false;
	}

#if WITH_EDITOR
	template<>
	ARGUS_API inline void IterateAllRecordsOfType<UArgusActorRecord>(const TFunctionRef<void(UArgusActorRecord*)>& function)
	{
		if (UArgusStaticDatabase* staticDatabase = GetParentDatabase())
		{
			staticDatabase->IterateAllUArgusActorRecords(function);
		}
	}

	static void RegisterNewUArgusActorRecordDatabase(UArgusActorRecordDatabase* database)
	{
		UArgusStaticDatabase* staticDatabase = GetParentDatabase();
		ARGUS_RETURN_ON_NULL(staticDatabase, ArgusStaticDataLog);
		staticDatabase->RegisterNewUArgusActorRecordDatabase(database);
	}
#endif //WITH_EDITOR
#pragma endregion

#pragma region UFactionRecord
	template<>
	ARGUS_API inline const UFactionRecord* GetRecord(uint32 id)
	{
		if (UArgusStaticDatabase* staticDatabase = UArgusStaticDatabase::GetInstance())
		{
			return staticDatabase->GetUFactionRecord(id);
		}

		return nullptr;
	}

	template<>
	ARGUS_API inline bool AsyncPreLoadRecord<UFactionRecord>(uint32 id, TFunction<void(const UFactionRecord*)> callback)
	{
		if (UArgusStaticDatabase* staticDatabase = UArgusStaticDatabase::GetInstance())
		{
			return staticDatabase->AsyncPreLoadUFactionRecord(id, callback);
		}

		return false;
	}

#if WITH_EDITOR
	template<>
	ARGUS_API inline void IterateAllRecordsOfType<UFactionRecord>(const TFunctionRef<void(UFactionRecord*)>& function)
	{
		if (UArgusStaticDatabase* staticDatabase = GetParentDatabase())
		{
			staticDatabase->IterateAllUFactionRecords(function);
		}
	}

	static void RegisterNewUFactionRecordDatabase(UFactionRecordDatabase* database)
	{
		UArgusStaticDatabase* staticDatabase = GetParentDatabase();
		ARGUS_RETURN_ON_NULL(staticDatabase, ArgusStaticDataLog);
		staticDatabase->RegisterNewUFactionRecordDatabase(database);
	}
#endif //WITH_EDITOR
#pragma endregion

#pragma region UMaterialRecord
	template<>
	ARGUS_API inline const UMaterialRecord* GetRecord(uint32 id)
	{
		if (UArgusStaticDatabase* staticDatabase = UArgusStaticDatabase::GetInstance())
		{
			return staticDatabase->GetUMaterialRecord(id);
		}

		return nullptr;
	}

	template<>
	ARGUS_API inline bool AsyncPreLoadRecord<UMaterialRecord>(uint32 id, TFunction<void(const UMaterialRecord*)> callback)
	{
		if (UArgusStaticDatabase* staticDatabase = UArgusStaticDatabase::GetInstance())
		{
			return staticDatabase->AsyncPreLoadUMaterialRecord(id, callback);
		}

		return false;
	}

#if WITH_EDITOR
	template<>
	ARGUS_API inline void IterateAllRecordsOfType<UMaterialRecord>(const TFunctionRef<void(UMaterialRecord*)>& function)
	{
		if (UArgusStaticDatabase* staticDatabase = GetParentDatabase())
		{
			staticDatabase->IterateAllUMaterialRecords(function);
		}
	}

	static void RegisterNewUMaterialRecordDatabase(UMaterialRecordDatabase* database)
	{
		UArgusStaticDatabase* staticDatabase = GetParentDatabase();
		ARGUS_RETURN_ON_NULL(staticDatabase, ArgusStaticDataLog);
		staticDatabase->RegisterNewUMaterialRecordDatabase(database);
	}
#endif //WITH_EDITOR
#pragma endregion

#pragma region UObstaclesRecord
	template<>
	ARGUS_API inline const UObstaclesRecord* GetRecord(uint32 id)
	{
		if (UArgusStaticDatabase* staticDatabase = UArgusStaticDatabase::GetInstance())
		{
			return staticDatabase->GetUObstaclesRecord(id);
		}

		return nullptr;
	}

	template<>
	ARGUS_API inline bool AsyncPreLoadRecord<UObstaclesRecord>(uint32 id, TFunction<void(const UObstaclesRecord*)> callback)
	{
		if (UArgusStaticDatabase* staticDatabase = UArgusStaticDatabase::GetInstance())
		{
			return staticDatabase->AsyncPreLoadUObstaclesRecord(id, callback);
		}

		return false;
	}

#if WITH_EDITOR
	template<>
	ARGUS_API inline void IterateAllRecordsOfType<UObstaclesRecord>(const TFunctionRef<void(UObstaclesRecord*)>& function)
	{
		if (UArgusStaticDatabase* staticDatabase = GetParentDatabase())
		{
			staticDatabase->IterateAllUObstaclesRecords(function);
		}
	}

	static void RegisterNewUObstaclesRecordDatabase(UObstaclesRecordDatabase* database)
	{
		UArgusStaticDatabase* staticDatabase = GetParentDatabase();
		ARGUS_RETURN_ON_NULL(staticDatabase, ArgusStaticDataLog);
		staticDatabase->RegisterNewUObstaclesRecordDatabase(database);
	}
#endif //WITH_EDITOR
#pragma endregion

#pragma region UPlacedArgusActorTeamInfoRecord
	template<>
	ARGUS_API inline const UPlacedArgusActorTeamInfoRecord* GetRecord(uint32 id)
	{
		if (UArgusStaticDatabase* staticDatabase = UArgusStaticDatabase::GetInstance())
		{
			return staticDatabase->GetUPlacedArgusActorTeamInfoRecord(id);
		}

		return nullptr;
	}

	template<>
	ARGUS_API inline bool AsyncPreLoadRecord<UPlacedArgusActorTeamInfoRecord>(uint32 id, TFunction<void(const UPlacedArgusActorTeamInfoRecord*)> callback)
	{
		if (UArgusStaticDatabase* staticDatabase = UArgusStaticDatabase::GetInstance())
		{
			return staticDatabase->AsyncPreLoadUPlacedArgusActorTeamInfoRecord(id, callback);
		}

		return false;
	}

#if WITH_EDITOR
	template<>
	ARGUS_API inline void IterateAllRecordsOfType<UPlacedArgusActorTeamInfoRecord>(const TFunctionRef<void(UPlacedArgusActorTeamInfoRecord*)>& function)
	{
		if (UArgusStaticDatabase* staticDatabase = GetParentDatabase())
		{
			staticDatabase->IterateAllUPlacedArgusActorTeamInfoRecords(function);
		}
	}

	static void RegisterNewUPlacedArgusActorTeamInfoRecordDatabase(UPlacedArgusActorTeamInfoRecordDatabase* database)
	{
		UArgusStaticDatabase* staticDatabase = GetParentDatabase();
		ARGUS_RETURN_ON_NULL(staticDatabase, ArgusStaticDataLog);
		staticDatabase->RegisterNewUPlacedArgusActorTeamInfoRecordDatabase(database);
	}
#endif //WITH_EDITOR
#pragma endregion

#pragma region UResourceSetRecord
	template<>
	ARGUS_API inline const UResourceSetRecord* GetRecord(uint32 id)
	{
		if (UArgusStaticDatabase* staticDatabase = UArgusStaticDatabase::GetInstance())
		{
			return staticDatabase->GetUResourceSetRecord(id);
		}

		return nullptr;
	}

	template<>
	ARGUS_API inline bool AsyncPreLoadRecord<UResourceSetRecord>(uint32 id, TFunction<void(const UResourceSetRecord*)> callback)
	{
		if (UArgusStaticDatabase* staticDatabase = UArgusStaticDatabase::GetInstance())
		{
			return staticDatabase->AsyncPreLoadUResourceSetRecord(id, callback);
		}

		return false;
	}

#if WITH_EDITOR
	template<>
	ARGUS_API inline void IterateAllRecordsOfType<UResourceSetRecord>(const TFunctionRef<void(UResourceSetRecord*)>& function)
	{
		if (UArgusStaticDatabase* staticDatabase = GetParentDatabase())
		{
			staticDatabase->IterateAllUResourceSetRecords(function);
		}
	}

	static void RegisterNewUResourceSetRecordDatabase(UResourceSetRecordDatabase* database)
	{
		UArgusStaticDatabase* staticDatabase = GetParentDatabase();
		ARGUS_RETURN_ON_NULL(staticDatabase, ArgusStaticDataLog);
		staticDatabase->RegisterNewUResourceSetRecordDatabase(database);
	}
#endif //WITH_EDITOR
#pragma endregion

#pragma region UTeamAlignmentRecord
	template<>
	ARGUS_API inline const UTeamAlignmentRecord* GetRecord(uint32 id)
	{
		if (UArgusStaticDatabase* staticDatabase = UArgusStaticDatabase::GetInstance())
		{
			return staticDatabase->GetUTeamAlignmentRecord(id);
		}

		return nullptr;
	}

	template<>
	ARGUS_API inline bool AsyncPreLoadRecord<UTeamAlignmentRecord>(uint32 id, TFunction<void(const UTeamAlignmentRecord*)> callback)
	{
		if (UArgusStaticDatabase* staticDatabase = UArgusStaticDatabase::GetInstance())
		{
			return staticDatabase->AsyncPreLoadUTeamAlignmentRecord(id, callback);
		}

		return false;
	}

#if WITH_EDITOR
	template<>
	ARGUS_API inline void IterateAllRecordsOfType<UTeamAlignmentRecord>(const TFunctionRef<void(UTeamAlignmentRecord*)>& function)
	{
		if (UArgusStaticDatabase* staticDatabase = GetParentDatabase())
		{
			staticDatabase->IterateAllUTeamAlignmentRecords(function);
		}
	}

	static void RegisterNewUTeamAlignmentRecordDatabase(UTeamAlignmentRecordDatabase* database)
	{
		UArgusStaticDatabase* staticDatabase = GetParentDatabase();
		ARGUS_RETURN_ON_NULL(staticDatabase, ArgusStaticDataLog);
		staticDatabase->RegisterNewUTeamAlignmentRecordDatabase(database);
	}
#endif //WITH_EDITOR
#pragma endregion

#pragma region UTeamColorRecord
	template<>
	ARGUS_API inline const UTeamColorRecord* GetRecord(uint32 id)
	{
		if (UArgusStaticDatabase* staticDatabase = UArgusStaticDatabase::GetInstance())
		{
			return staticDatabase->GetUTeamColorRecord(id);
		}

		return nullptr;
	}

	template<>
	ARGUS_API inline bool AsyncPreLoadRecord<UTeamColorRecord>(uint32 id, TFunction<void(const UTeamColorRecord*)> callback)
	{
		if (UArgusStaticDatabase* staticDatabase = UArgusStaticDatabase::GetInstance())
		{
			return staticDatabase->AsyncPreLoadUTeamColorRecord(id, callback);
		}

		return false;
	}

#if WITH_EDITOR
	template<>
	ARGUS_API inline void IterateAllRecordsOfType<UTeamColorRecord>(const TFunctionRef<void(UTeamColorRecord*)>& function)
	{
		if (UArgusStaticDatabase* staticDatabase = GetParentDatabase())
		{
			staticDatabase->IterateAllUTeamColorRecords(function);
		}
	}

	static void RegisterNewUTeamColorRecordDatabase(UTeamColorRecordDatabase* database)
	{
		UArgusStaticDatabase* staticDatabase = GetParentDatabase();
		ARGUS_RETURN_ON_NULL(staticDatabase, ArgusStaticDataLog);
		staticDatabase->RegisterNewUTeamColorRecordDatabase(database);
	}
#endif //WITH_EDITOR
#pragma endregion

#pragma region UWorldCellRecord
	template<>
	ARGUS_API inline const UWorldCellRecord* GetRecord(uint32 id)
	{
		if (UArgusStaticDatabase* staticDatabase = UArgusStaticDatabase::GetInstance())
		{
			return staticDatabase->GetUWorldCellRecord(id);
		}

		return nullptr;
	}

	template<>
	ARGUS_API inline bool AsyncPreLoadRecord<UWorldCellRecord>(uint32 id, TFunction<void(const UWorldCellRecord*)> callback)
	{
		if (UArgusStaticDatabase* staticDatabase = UArgusStaticDatabase::GetInstance())
		{
			return staticDatabase->AsyncPreLoadUWorldCellRecord(id, callback);
		}

		return false;
	}

#if WITH_EDITOR
	template<>
	ARGUS_API inline void IterateAllRecordsOfType<UWorldCellRecord>(const TFunctionRef<void(UWorldCellRecord*)>& function)
	{
		if (UArgusStaticDatabase* staticDatabase = GetParentDatabase())
		{
			staticDatabase->IterateAllUWorldCellRecords(function);
		}
	}

	static void RegisterNewUWorldCellRecordDatabase(UWorldCellRecordDatabase* database)
	{
		UArgusStaticDatabase* staticDatabase = GetParentDatabase();
		ARGUS_RETURN_ON_NULL(staticDatabase, ArgusStaticDataLog);
		staticDatabase->RegisterNewUWorldCellRecordDatabase(database);
	}
#endif //WITH_EDITOR
#pragma endregion

#if WITH_EDITOR
private:
	static UArgusStaticDatabase* GetParentDatabase();
#endif //WITH_EDITOR
};
