// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ArgusStaticDatabase.h"

#pragma region UAbilityRecord
const UAbilityRecord* UArgusStaticDatabase::GetUAbilityRecord(uint32 id)
{
	if (!m_UAbilityRecordDatabasePersistent)
	{
		m_UAbilityRecordDatabasePersistent = m_UAbilityRecordDatabase.LoadSynchronous();
		m_UAbilityRecordDatabasePersistent->ResizePersistentObjectPointerArray();
	}

	if (!m_UAbilityRecordDatabasePersistent)
	{
		ARGUS_LOG
		(
			ArgusStaticDataLog, Error,
			TEXT("[%s] Could not retrieve %s. %s might not be properly assigned."),
			ARGUS_FUNCNAME,
			ARGUS_NAMEOF(m_UAbilityRecordDatabasePersistent),
			ARGUS_NAMEOF(m_UAbilityRecordDatabase)
		);
		return nullptr;
	}

	return m_UAbilityRecordDatabasePersistent->GetRecord(id);
}
#pragma endregion
#pragma region UArgusActorRecord
const UArgusActorRecord* UArgusStaticDatabase::GetUArgusActorRecord(uint32 id)
{
	if (!m_UArgusActorRecordDatabasePersistent)
	{
		m_UArgusActorRecordDatabasePersistent = m_UArgusActorRecordDatabase.LoadSynchronous();
		m_UArgusActorRecordDatabasePersistent->ResizePersistentObjectPointerArray();
	}

	if (!m_UArgusActorRecordDatabasePersistent)
	{
		ARGUS_LOG
		(
			ArgusStaticDataLog, Error,
			TEXT("[%s] Could not retrieve %s. %s might not be properly assigned."),
			ARGUS_FUNCNAME,
			ARGUS_NAMEOF(m_UArgusActorRecordDatabasePersistent),
			ARGUS_NAMEOF(m_UArgusActorRecordDatabase)
		);
		return nullptr;
	}

	return m_UArgusActorRecordDatabasePersistent->GetRecord(id);
}
#pragma endregion
#pragma region UFactionRecord
const UFactionRecord* UArgusStaticDatabase::GetUFactionRecord(uint32 id)
{
	if (!m_UFactionRecordDatabasePersistent)
	{
		m_UFactionRecordDatabasePersistent = m_UFactionRecordDatabase.LoadSynchronous();
		m_UFactionRecordDatabasePersistent->ResizePersistentObjectPointerArray();
	}

	if (!m_UFactionRecordDatabasePersistent)
	{
		ARGUS_LOG
		(
			ArgusStaticDataLog, Error,
			TEXT("[%s] Could not retrieve %s. %s might not be properly assigned."),
			ARGUS_FUNCNAME,
			ARGUS_NAMEOF(m_UFactionRecordDatabasePersistent),
			ARGUS_NAMEOF(m_UFactionRecordDatabase)
		);
		return nullptr;
	}

	return m_UFactionRecordDatabasePersistent->GetRecord(id);
}
#pragma endregion
#pragma region UTeamColorRecord
const UTeamColorRecord* UArgusStaticDatabase::GetUTeamColorRecord(uint32 id)
{
	if (!m_UTeamColorRecordDatabasePersistent)
	{
		m_UTeamColorRecordDatabasePersistent = m_UTeamColorRecordDatabase.LoadSynchronous();
		m_UTeamColorRecordDatabasePersistent->ResizePersistentObjectPointerArray();
	}

	if (!m_UTeamColorRecordDatabasePersistent)
	{
		ARGUS_LOG
		(
			ArgusStaticDataLog, Error,
			TEXT("[%s] Could not retrieve %s. %s might not be properly assigned."),
			ARGUS_FUNCNAME,
			ARGUS_NAMEOF(m_UTeamColorRecordDatabasePersistent),
			ARGUS_NAMEOF(m_UTeamColorRecordDatabase)
		);
		return nullptr;
	}

	return m_UTeamColorRecordDatabasePersistent->GetRecord(id);
}
#pragma endregion
