// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ArgusLogging.h"
#include "ArgusMacros.h"
#include "RecordDatabases/FactionRecordDatabase.h"
#include "ArgusStaticDatabase.generated.h"

UCLASS()
class UArgusStaticDatabase : public UDataAsset
{
	GENERATED_BODY()

#pragma region UFactionRecord
public:
	const UFactionRecord* GetUFactionRecord(uint32 id);
	const uint32 GetIdFromRecordSoftPtr(const TSoftObjectPtr<UFactionRecord>& UFactionRecord);

protected:
	UPROPERTY(EditAnywhere)
	TSoftObjectPtr<UFactionRecordDatabase> m_UFactionRecordDatabase;
	UPROPERTY(Transient)
	TObjectPtr<UFactionRecordDatabase> m_UFactionRecordDatabasePersistent;
#pragma endregion
};
