// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ArgusLogging.h"
#include "ArgusMacros.h"
#include "RecordDatabases/AbilityRecordDatabase.h"
#include "RecordDatabases/ArgusActorRecordDatabase.h"
#include "RecordDatabases/FactionRecordDatabase.h"
#include "RecordDatabases/PlacedArgusActorTeamInfoRecordDatabase.h"
#include "RecordDatabases/TeamColorRecordDatabase.h"
#include "ArgusStaticDatabase.generated.h"

UCLASS()
class UArgusStaticDatabase : public UDataAsset
{
	GENERATED_BODY()

#pragma region UAbilityRecord
public:
	const UAbilityRecord* GetUAbilityRecord(uint32 id);

protected:
	UPROPERTY(EditAnywhere)
	TSoftObjectPtr<UAbilityRecordDatabase> m_UAbilityRecordDatabase;
	UPROPERTY(Transient)
	TObjectPtr<UAbilityRecordDatabase> m_UAbilityRecordDatabasePersistent;
#pragma endregion
#pragma region UArgusActorRecord
public:
	const UArgusActorRecord* GetUArgusActorRecord(uint32 id);

protected:
	UPROPERTY(EditAnywhere)
	TSoftObjectPtr<UArgusActorRecordDatabase> m_UArgusActorRecordDatabase;
	UPROPERTY(Transient)
	TObjectPtr<UArgusActorRecordDatabase> m_UArgusActorRecordDatabasePersistent;
#pragma endregion
#pragma region UFactionRecord
public:
	const UFactionRecord* GetUFactionRecord(uint32 id);

protected:
	UPROPERTY(EditAnywhere)
	TSoftObjectPtr<UFactionRecordDatabase> m_UFactionRecordDatabase;
	UPROPERTY(Transient)
	TObjectPtr<UFactionRecordDatabase> m_UFactionRecordDatabasePersistent;
#pragma endregion
#pragma region UPlacedArgusActorTeamInfoRecord
public:
	const UPlacedArgusActorTeamInfoRecord* GetUPlacedArgusActorTeamInfoRecord(uint32 id);

protected:
	UPROPERTY(EditAnywhere)
	TSoftObjectPtr<UPlacedArgusActorTeamInfoRecordDatabase> m_UPlacedArgusActorTeamInfoRecordDatabase;
	UPROPERTY(Transient)
	TObjectPtr<UPlacedArgusActorTeamInfoRecordDatabase> m_UPlacedArgusActorTeamInfoRecordDatabasePersistent;
#pragma endregion
#pragma region UTeamColorRecord
public:
	const UTeamColorRecord* GetUTeamColorRecord(uint32 id);

protected:
	UPROPERTY(EditAnywhere)
	TSoftObjectPtr<UTeamColorRecordDatabase> m_UTeamColorRecordDatabase;
	UPROPERTY(Transient)
	TObjectPtr<UTeamColorRecordDatabase> m_UTeamColorRecordDatabasePersistent;
#pragma endregion
};
