// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ArgusStaticDatabase.h"

#pragma region UFactionRecord
const UFactionRecord* UArgusStaticDatabase::GetUFactionRecord(uint32 id)
{
	if (!m_UFactionRecordDatabasePersistent)
	{
		m_UFactionRecordDatabasePersistent = m_UFactionRecordDatabase.LoadSynchronous();
		m_UFactionRecordDatabasePersistent->ResizePersistentObjectPointerArray();
	}

	if (!m_UFactionRecordDatabasePersistent)
	{
		UE_LOG
		(
			ArgusStaticDataLog, Error,
			TEXT("[%s] Could not retrieve %s. %s might not be properly assigned."),
			ARGUS_FUNCNAME,
			ARGUS_NAMEOF(m_UFactionRecordDatabasePersistent),
			ARGUS_NAMEOF(m_UFactionRecordDatabase)
		);
		return nullptr;
	}

	return m_UFactionRecordDatabasePersistent->GetRecord(id);
}

const uint32 UArgusStaticDatabase::GetIdFromRecordSoftPtr(const TSoftObjectPtr<UFactionRecord>& UFactionRecord)
{
	if (!m_UFactionRecordDatabasePersistent)
	{
		m_UFactionRecordDatabasePersistent = m_UFactionRecordDatabase.LoadSynchronous();
		m_UFactionRecordDatabasePersistent->ResizePersistentObjectPointerArray();
	}

	if (!m_UFactionRecordDatabasePersistent)
	{
		UE_LOG
		(
			ArgusStaticDataLog, Error,
			TEXT("[%s] Could not retrieve %s. %s might not be properly assigned."),
			ARGUS_FUNCNAME,
			ARGUS_NAMEOF(m_UFactionRecordDatabasePersistent),
			ARGUS_NAMEOF(m_UFactionRecordDatabase)
		);
		return 0u;
	}

	return m_UFactionRecordDatabasePersistent->GetIdFromRecordSoftPtr(UFactionRecord);
}
#pragma endregion
