// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ArgusStaticData.h"

#if WITH_EDITOR
#include "Editor.h"
#include "Subsystems/EditorAssetSubsystem.h"

#include "RecordDatabases/AbilityRecordDatabase.h"
#include "RecordDatabases/ArgusActorRecordDatabase.h"
#include "RecordDatabases/FactionRecordDatabase.h"
#include "RecordDatabases/MaterialRecordDatabase.h"
#include "RecordDatabases/PlacedArgusActorTeamInfoRecordDatabase.h"
#include "RecordDatabases/ResourceSetRecordDatabase.h"
#include "RecordDatabases/TeamAlignmentRecordDatabase.h"
#include "RecordDatabases/TeamColorRecordDatabase.h"
 
uint32 ArgusStaticData::AddRecordToDatabase(UArgusStaticRecord* record)
{
	UArgusStaticDatabase* staticDatabase = GetParentDatabase();
	if (!staticDatabase)
	{
		return 0u;
	}

	if (UAbilityRecord* UAbilityRecordInstance = Cast<UAbilityRecord>(record))
	{
		return staticDatabase->AddUAbilityRecordToDatabase(UAbilityRecordInstance);
	}
	if (UArgusActorRecord* UArgusActorRecordInstance = Cast<UArgusActorRecord>(record))
	{
		return staticDatabase->AddUArgusActorRecordToDatabase(UArgusActorRecordInstance);
	}
	if (UFactionRecord* UFactionRecordInstance = Cast<UFactionRecord>(record))
	{
		return staticDatabase->AddUFactionRecordToDatabase(UFactionRecordInstance);
	}
	if (UMaterialRecord* UMaterialRecordInstance = Cast<UMaterialRecord>(record))
	{
		return staticDatabase->AddUMaterialRecordToDatabase(UMaterialRecordInstance);
	}
	if (UPlacedArgusActorTeamInfoRecord* UPlacedArgusActorTeamInfoRecordInstance = Cast<UPlacedArgusActorTeamInfoRecord>(record))
	{
		return staticDatabase->AddUPlacedArgusActorTeamInfoRecordToDatabase(UPlacedArgusActorTeamInfoRecordInstance);
	}
	if (UResourceSetRecord* UResourceSetRecordInstance = Cast<UResourceSetRecord>(record))
	{
		return staticDatabase->AddUResourceSetRecordToDatabase(UResourceSetRecordInstance);
	}
	if (UTeamAlignmentRecord* UTeamAlignmentRecordInstance = Cast<UTeamAlignmentRecord>(record))
	{
		return staticDatabase->AddUTeamAlignmentRecordToDatabase(UTeamAlignmentRecordInstance);
	}
	if (UTeamColorRecord* UTeamColorRecordInstance = Cast<UTeamColorRecord>(record))
	{
		return staticDatabase->AddUTeamColorRecordToDatabase(UTeamColorRecordInstance);
	}

	return 0u;
}

UArgusStaticDatabase* ArgusStaticData::GetParentDatabase()
{
	// TODO JAMES: Refactor this to use PrimaryDataAsset loading style.

	if (!GEditor)
	{
		return nullptr;
	}

	UEditorAssetSubsystem* editorAssetSubsystem = GEditor->GetEditorSubsystem<UEditorAssetSubsystem>();
	if (!editorAssetSubsystem)
	{
		return nullptr;
	}

	return Cast<UArgusStaticDatabase>(editorAssetSubsystem->LoadAsset(FString("/Game/StaticData/ArgusStaticDatabase.ArgusStaticDatabase")));
}
#endif //WITH_EDITOR