// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#define EDITOR_MODULE_FRIENDS	friend class FAssetTypeActions_ArgusEntityTemplate; \
								friend class FAssetTypeActions_HealthComponentData; \
								friend class FAssetTypeActions_AbilityRecord;