// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "DataComponentDefinitions/ArgusDecalComponentData.h"
#include "Developer/AssetTools/Public/AssetTypeActions_Base.h"
#include "Editor/UnrealEd/Classes/Factories/Factory.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "ArgusDecalComponentDataFactory.generated.h"

#define LOCTEXT_NAMESPACE "ArgusDecalComponentDataFactory"

UCLASS()
class UArgusDecalComponentDataFactory : public UFactory
{
	GENERATED_BODY()

public:
	UArgusDecalComponentDataFactory(const FObjectInitializer& objectInitializer);
	virtual UObject* FactoryCreateNew(UClass* classDefinition, UObject* parentObject, FName name, EObjectFlags objectFlags, UObject* context, FFeedbackContext* warning) override;

protected:
	virtual bool IsMacroFactory() const { return false; }
};

class FAssetTypeActions_ArgusDecalComponentData : public FAssetTypeActions_Base
{
public:
	virtual FText GetName() const override { return LOCTEXT("ArgusDecalComponentData", "ArgusDecalComponent Data"); }
	virtual uint32 GetCategories() override;
	virtual FColor GetTypeColor() const override { return FColor(239, 144, 58); }

	virtual FText GetAssetDescription(const FAssetData& assetData) const override { return LOCTEXT("ArgusDecalComponentDataDesc", "Data Asset that defines the contents of a ArgusDecalComponent."); }
	virtual UClass* GetSupportedClass() const override { return UArgusDecalComponentData::StaticClass(); }
	virtual const TArray<FText>& GetSubMenus() const override { return m_subMenus; };

private:
	TArray<FText> m_subMenus{ LOCTEXT("ComponentSubmenu", "Component Data") };
};


#undef LOCTEXT_NAMESPACE
