// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "IdentityComponentDataFactory.h"
#include "ArgusEditorModule.h"

UIdentityComponentDataFactory::UIdentityComponentDataFactory(const FObjectInitializer& objectInitializer)
{
	SupportedClass = UIdentityComponentData::StaticClass();
	bEditAfterNew = true;
	bCreateNew = true;
}

UObject* UIdentityComponentDataFactory::FactoryCreateNew(UClass* classDefinition, UObject* parentObject, FName name, EObjectFlags objectFlags, UObject* context, FFeedbackContext* warning)
{
	if (!ensure(classDefinition) || !ensure(classDefinition->IsChildOf(SupportedClass)))
	{
		return nullptr;
	}

	return NewObject<UObject>(parentObject, SupportedClass, name, objectFlags | RF_Transactional, context);
}

uint32 FAssetTypeActions_IdentityComponentData::GetCategories()
{
	return ArgusEditorModule::GetAssetTypeCategory();
}
