// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ComponentDefinitions/AbilityComponent.h"
#include "ArgusComponentRegistry.h"

// Component shared functionality
uint16 AbilityComponent::GetOwningEntityId() const
{
	return this - &ArgusComponentRegistry::s_AbilityComponents[0];
}

// Per observable logic
