// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ComponentDefinitions/AbilityComponent.h"
#include "ArgusEntity.h"

#if !UE_BUILD_SHIPPING
#include "imgui.h"
#include "UObject/ReflectedTypeAccessors.h"
#endif //!UE_BUILD_SHIPPING

// Component shared functionality
uint16 AbilityComponent::GetOwningEntityId() const
{
	return this - &ArgusComponentRegistry::s_AbilityComponents[0];
}

void AbilityComponent::DrawComponentDebug() const
{
#if !UE_BUILD_SHIPPING
	if (!ImGui::CollapsingHeader("AbilityComponent"))
	{
		return;
	}

	if (ImGui::BeginTable("ComponentValues", 2, ImGuiTableFlags_NoSavedSettings))
	{
		ImGui::TableNextColumn();
		ImGui::Text("m_ability0Id");
		ImGui::TableNextColumn();
		ImGui::Text("%d", m_ability0Id);
		ImGui::TableNextColumn();
		ImGui::Text("m_ability1Id");
		ImGui::TableNextColumn();
		ImGui::Text("%d", m_ability1Id);
		ImGui::TableNextColumn();
		ImGui::Text("m_ability2Id");
		ImGui::TableNextColumn();
		ImGui::Text("%d", m_ability2Id);
		ImGui::TableNextColumn();
		ImGui::Text("m_ability3Id");
		ImGui::TableNextColumn();
		ImGui::Text("%d", m_ability3Id);
		ImGui::EndTable();
	}
#endif //!UE_BUILD_SHIPPING
}

// Per observable logic
