// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ComponentDefinitions/ArgusDecalComponent.h"
#include "ArgusEntity.h"
#include "ArgusLogging.h"

#if !UE_BUILD_SHIPPING
#include "ArgusStaticData.h"
#include "imgui.h"
#include "UObject/ReflectedTypeAccessors.h"
#endif //!UE_BUILD_SHIPPING

// Component shared functionality
uint16 ArgusDecalComponent::GetOwningEntityId() const
{
	return this - &ArgusComponentRegistry::s_ArgusDecalComponents[0];
}

void ArgusDecalComponent::Reset()
{
	m_lifetimeSeconds = 1.0f;
	m_referencingEntityCount = 0u;
	m_connectedEntityId = ArgusECSConstants::k_maxEntities;
	m_lifetimeTimer.Reset();
	m_decalType = EDecalType::MoveToLocation;
}

void ArgusDecalComponent::DrawComponentDebug() const
{
#if !UE_BUILD_SHIPPING
	if (!ImGui::CollapsingHeader("ArgusDecalComponent"))
	{
		return;
	}

	if (ImGui::BeginTable("ComponentValues", 2, ImGuiTableFlags_NoSavedSettings))
	{
		ImGui::TableNextColumn();
		ImGui::Text("m_lifetimeSeconds");
		ImGui::TableNextColumn();
		ImGui::Text("%.2f", m_lifetimeSeconds);
		ImGui::TableNextColumn();
		ImGui::Text("m_referencingEntityCount");
		ImGui::TableNextColumn();
		ImGui::Text("%d", m_referencingEntityCount);
		ImGui::TableNextColumn();
		ImGui::Text("m_connectedEntityId");
		ImGui::TableNextColumn();
		ImGui::Text("%d", m_connectedEntityId);
		ImGui::TableNextColumn();
		ImGui::Text("m_lifetimeTimer");
		ImGui::TableNextColumn();
		const ArgusEntity owningEntity = ArgusEntity::RetrieveEntity(GetOwningEntityId());
		if (m_lifetimeTimer.IsTimerTicking(owningEntity))
		{
			ImGui::Text("%.2f", m_lifetimeTimer.GetTimeRemaining(owningEntity));
			ImGui::SameLine();
			ImGui::ProgressBar(m_lifetimeTimer.GetTimeElapsedProportion(owningEntity));
		}
		else if (m_lifetimeTimer.IsTimerComplete(owningEntity))
		{
			ImGui::Text("Timer complete");
		}
		else
		{
			ImGui::Text("Not set");
		}
		ImGui::TableNextColumn();
		ImGui::Text("m_decalType");
		ImGui::TableNextColumn();
		const char* valueName_m_decalType = ARGUS_FSTRING_TO_CHAR(StaticEnum<EDecalType>()->GetNameStringByValue(static_cast<uint8>(m_decalType)))
		ImGui::Text(valueName_m_decalType);
		ImGui::EndTable();
	}
#endif //!UE_BUILD_SHIPPING
}

// Per observable logic
