// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ComponentDefinitions/AvoidanceGroupingComponent.h"
#include "ArgusComponentRegistry.h"

// Component shared functionality
uint16 AvoidanceGroupingComponent::GetOwningEntityId() const
{
	return this - &ArgusComponentRegistry::s_AvoidanceGroupingComponents[0];
}

// Per observable logic
