// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ComponentDefinitions/AvoidanceGroupingComponent.h"
#include "ArgusEntity.h"
#include "ArgusLogging.h"
#include "Serialization/Archive.h"

#if !UE_BUILD_SHIPPING
#include "ArgusStaticData.h"
#include "imgui.h"
#include "UObject/ReflectedTypeAccessors.h"
#endif //!UE_BUILD_SHIPPING

// Component shared functionality
uint16 AvoidanceGroupingComponent::GetOwningEntityId() const
{
	return this - &ArgusComponentRegistry::s_AvoidanceGroupingComponents[0];
}

void AvoidanceGroupingComponent::Reset()
{
	m_groupAverageLocation = FVector::ZeroVector;
	m_entityIdsInGroup.Reset();
	m_groupId = ArgusECSConstants::k_maxEntities;
	m_numberOfIdleEntities = 0u;
	m_avoidancePriority = EAvoidancePriority::Lowest;
}

void AvoidanceGroupingComponent::Serialize(FArchive& archive)
{
}

void AvoidanceGroupingComponent::DrawComponentDebug() const
{
#if !UE_BUILD_SHIPPING
	if (!ImGui::CollapsingHeader("AvoidanceGroupingComponent"))
	{
		return;
	}

	if (ImGui::BeginTable("ComponentValues", 2, ImGuiTableFlags_NoSavedSettings | ImGuiTableFlags_BordersInner))
	{
		ImGui::TableNextColumn();
		ImGui::Text("m_groupAverageLocation");
		ImGui::TableNextColumn();
		ImGui::Text("(%.2f, %.2f, %.2f)", m_groupAverageLocation.X, m_groupAverageLocation.Y, m_groupAverageLocation.Z);
		ImGui::TableNextColumn();
		ImGui::Text("m_entityIdsInGroup");
		ImGui::TableNextColumn();
		ImGui::Text("Array max is currently = %d", m_entityIdsInGroup.Max());
		if (m_entityIdsInGroup.Num() == 0)
		{
			ImGui::Text("Array is empty");
		}
		else
		{
			ImGui::Text("Size of array = %d", m_entityIdsInGroup.Num());
			ImGui::Indent();
			for (int32 i = 0; i < m_entityIdsInGroup.Num(); ++i)
			{
				if (i != 0) ImGui::Separator();
				ImGui::Text("%d", m_entityIdsInGroup[i]);
			}
			ImGui::Unindent();
		}
		ImGui::TableNextColumn();
		ImGui::Text("m_groupId");
		ImGui::TableNextColumn();
		ImGui::Text("%d", m_groupId);
		ImGui::TableNextColumn();
		ImGui::Text("m_numberOfIdleEntities");
		ImGui::TableNextColumn();
		ImGui::Text("%d", m_numberOfIdleEntities);
		ImGui::TableNextColumn();
		ImGui::Text("m_avoidancePriority");
		ImGui::TableNextColumn();
		const char* valueName_m_avoidancePriority = ARGUS_FSTRING_TO_CHAR(StaticEnum<EAvoidancePriority>()->GetNameStringByValue(static_cast<uint8>(m_avoidancePriority)))
		ImGui::Text(valueName_m_avoidancePriority);
		ImGui::EndTable();
	}
#endif //!UE_BUILD_SHIPPING
}

// Per observable logic
