// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ComponentDefinitions/ConstructionComponent.h"
#include "ArgusComponentRegistry.h"

// Component shared functionality
uint16 ConstructionComponent::GetOwningEntityId() const
{
	return this - &ArgusComponentRegistry::s_ConstructionComponents[0];
}

// Per observable logic
