// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ComponentDefinitions/FogOfWarLocationComponent.h"
#include "ArgusEntity.h"
#include "ArgusLogging.h"

#if !UE_BUILD_SHIPPING
#include "ArgusStaticData.h"
#include "imgui.h"
#include "UObject/ReflectedTypeAccessors.h"
#endif //!UE_BUILD_SHIPPING

// Component shared functionality
uint16 FogOfWarLocationComponent::GetOwningEntityId() const
{
	return this - &ArgusComponentRegistry::s_FogOfWarLocationComponents[0];
}

void FogOfWarLocationComponent::Reset()
{
	m_fogOfWarPixel = MAX_uint32;
	m_clearedThisFrame = false;
	m_needsActivelyRevealedThisFrame = false;
	m_updatedPixelThisFrame = false;
}

void FogOfWarLocationComponent::DrawComponentDebug() const
{
#if !UE_BUILD_SHIPPING
	if (!ImGui::CollapsingHeader("FogOfWarLocationComponent"))
	{
		return;
	}

	if (ImGui::BeginTable("ComponentValues", 2, ImGuiTableFlags_NoSavedSettings))
	{
		ImGui::TableNextColumn();
		ImGui::Text("m_fogOfWarPixel");
		ImGui::TableNextColumn();
		ImGui::Text("%d", m_fogOfWarPixel);
		ImGui::TableNextColumn();
		ImGui::Text("m_clearedThisFrame");
		ImGui::TableNextColumn();
		ImGui::Text(m_clearedThisFrame ? "true" : "false");
		ImGui::TableNextColumn();
		ImGui::Text("m_needsActivelyRevealedThisFrame");
		ImGui::TableNextColumn();
		ImGui::Text(m_needsActivelyRevealedThisFrame ? "true" : "false");
		ImGui::TableNextColumn();
		ImGui::Text("m_updatedPixelThisFrame");
		ImGui::TableNextColumn();
		ImGui::Text(m_updatedPixelThisFrame ? "true" : "false");
		ImGui::EndTable();
	}
#endif //!UE_BUILD_SHIPPING
}

// Per observable logic
