// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ComponentDefinitions/IdentityComponent.h"
#include "ArgusComponentRegistry.h"

// Component shared functionality

// Per observable logic
