// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ComponentDefinitions/IdentityComponent.h"
#include "ArgusEntity.h"

#if !UE_BUILD_SHIPPING
#include "imgui.h"
#include "UObject/ReflectedTypeAccessors.h"
#endif //!UE_BUILD_SHIPPING

// Component shared functionality
uint16 IdentityComponent::GetOwningEntityId() const
{
	return this - &ArgusComponentRegistry::s_IdentityComponents[0];
}

void IdentityComponent::DrawComponentDebug() const
{
#if !UE_BUILD_SHIPPING
	if (!ImGui::CollapsingHeader("IdentityComponent"))
	{
		return;
	}

	if (ImGui::BeginTable("ComponentValues", 2, ImGuiTableFlags_NoSavedSettings))
	{
		ImGui::TableNextColumn();
		ImGui::Text("m_factionId");
		ImGui::TableNextColumn();
		ImGui::Text("%d", m_factionId);
		ImGui::TableNextColumn();
		ImGui::Text("m_team");
		ImGui::TableNextColumn();
		const char* valueName_m_team = ARGUS_FSTRING_TO_CHAR(StaticEnum<ETeam>()->GetNameStringByValue(static_cast<uint8>(m_team)))
		ImGui::Text(valueName_m_team);
		ImGui::TableNextColumn();
		ImGui::Text("m_allies");
		ImGui::TableNextColumn();
		ImGui::Text("%d", m_allies);
		ImGui::TableNextColumn();
		ImGui::Text("m_enemies");
		ImGui::TableNextColumn();
		ImGui::Text("%d", m_enemies);
		ImGui::EndTable();
	}
#endif //!UE_BUILD_SHIPPING
}

// Per observable logic
