// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ComponentDefinitions/IdentityComponent.h"
#include "ArgusEntity.h"
#include "ArgusLogging.h"
#include "ArgusMath.h"
#include "Serialization/Archive.h"

#if !UE_BUILD_SHIPPING
#include "ArgusStaticData.h"
#include "imgui.h"
#include "UObject/ReflectedTypeAccessors.h"
#endif //!UE_BUILD_SHIPPING

// Component shared functionality
uint16 IdentityComponent::GetOwningEntityId() const
{
	return this - &ArgusComponentRegistry::s_IdentityComponents[0];
}

void IdentityComponent::Reset()
{
	m_factionId = 0u;
	m_team = ETeam::None;
	m_seenBy = 0u;
	m_everSeenBy = 0u;
}

void IdentityComponent::Serialize(FArchive& archive)
{
	archive << m_factionId;
	archive << m_team;
	archive << m_seenBy;
	archive << m_everSeenBy;
}

void IdentityComponent::DrawComponentDebug() const
{
#if !UE_BUILD_SHIPPING
	if (!ImGui::CollapsingHeader("IdentityComponent"))
	{
		return;
	}

	if (ImGui::BeginTable("ComponentValues", 2, ImGuiTableFlags_NoSavedSettings | ImGuiTableFlags_BordersInner))
	{
		ImGui::TableNextColumn();
		ImGui::Text("m_factionId");
		ImGui::TableNextColumn();
		if (m_factionId != 0u)
		{
			if (const UFactionRecord* record_m_factionId = ArgusStaticData::GetRecord<UFactionRecord>(m_factionId))
			{
				const char* name_m_factionId = ARGUS_FSTRING_TO_CHAR(record_m_factionId->GetName());
				ImGui::Text("%s", name_m_factionId);
			}
		}
		else
		{
			ImGui::Text("None");
		}
		ImGui::TableNextColumn();
		ImGui::Text("m_team");
		ImGui::TableNextColumn();
		const char* valueName_m_team = ARGUS_FSTRING_TO_CHAR(StaticEnum<ETeam>()->GetNameStringByValue(static_cast<uint8>(m_team)));
		ImGui::Text(valueName_m_team);
		ImGui::TableNextColumn();
		ImGui::Text("m_seenBy");
		ImGui::TableNextColumn();
		uint8 enumSize_m_seenBy = sizeof(ETeam) * 8u;
		bool triggered_m_seenBy = false;
		for (uint8 i = 0u; i < enumSize_m_seenBy; ++i)
		{
			uint32 enumValue_m_seenBy = 1 << i;
			if (m_seenBy & enumValue_m_seenBy)
			{
				if (triggered_m_seenBy)
				{
					ImGui::SameLine();
				}
				const char* valueName_m_seenBy = ARGUS_FSTRING_TO_CHAR(StaticEnum<ETeam>()->GetNameStringByValue(enumValue_m_seenBy));
				ImGui::Text("%s, ", valueName_m_seenBy);
				triggered_m_seenBy = true;
			}
		}
		ImGui::TableNextColumn();
		ImGui::Text("m_everSeenBy");
		ImGui::TableNextColumn();
		uint8 enumSize_m_everSeenBy = sizeof(ETeam) * 8u;
		bool triggered_m_everSeenBy = false;
		for (uint8 i = 0u; i < enumSize_m_everSeenBy; ++i)
		{
			uint32 enumValue_m_everSeenBy = 1 << i;
			if (m_everSeenBy & enumValue_m_everSeenBy)
			{
				if (triggered_m_everSeenBy)
				{
					ImGui::SameLine();
				}
				const char* valueName_m_everSeenBy = ARGUS_FSTRING_TO_CHAR(StaticEnum<ETeam>()->GetNameStringByValue(enumValue_m_everSeenBy));
				ImGui::Text("%s, ", valueName_m_everSeenBy);
				triggered_m_everSeenBy = true;
			}
		}
		ImGui::EndTable();
	}
#endif //!UE_BUILD_SHIPPING
}

// Per observable logic
