// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ComponentDefinitions/NavigationComponent.h"
#include "ArgusComponentRegistry.h"

// Component shared functionality
uint16 NavigationComponent::GetOwningEntityId() const
{
	return this - &ArgusComponentRegistry::s_NavigationComponents[0];
}

// Per observable logic
