// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ComponentDefinitions/NearbyObstaclesComponent.h"
#include "ArgusEntity.h"
#include "ArgusLogging.h"

#if !UE_BUILD_SHIPPING
#include "ArgusStaticData.h"
#include "imgui.h"
#include "UObject/ReflectedTypeAccessors.h"
#endif //!UE_BUILD_SHIPPING

// Component shared functionality
uint16 NearbyObstaclesComponent::GetOwningEntityId() const
{
	return this - &ArgusComponentRegistry::s_NearbyObstaclesComponents[0];
}

void NearbyObstaclesComponent::Reset()
{
	m_obstacleIndiciesInSightRange.Reset();
}

void NearbyObstaclesComponent::DrawComponentDebug() const
{
#if !UE_BUILD_SHIPPING
	if (!ImGui::CollapsingHeader("NearbyObstaclesComponent"))
	{
		return;
	}

	if (ImGui::BeginTable("ComponentValues", 2, ImGuiTableFlags_NoSavedSettings))
	{
		ImGui::TableNextColumn();
		ImGui::Text("m_obstacleIndiciesInSightRange");
		ImGui::TableNextColumn();
		ImGui::Text("Array max is currently = %d", m_obstacleIndiciesInSightRange.Max());
		if (m_obstacleIndiciesInSightRange.Num() == 0)
		{
			ImGui::Text("Array is empty");
		}
		else
		{
			ImGui::Text("Size of array = %d", m_obstacleIndiciesInSightRange.Num());
			for (int32 i = 0; i < m_obstacleIndiciesInSightRange.Num(); ++i)
			{
			}
		}
		ImGui::EndTable();
	}
#endif //!UE_BUILD_SHIPPING
}

// Per observable logic
