// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ComponentDefinitions/ObserversComponent.h"
#include "ArgusComponentRegistry.h"

#if !UE_BUILD_SHIPPING
#include "imgui.h"
#endif //!UE_BUILD_SHIPPING

// Component shared functionality
uint16 ObserversComponent::GetOwningEntityId() const
{
	return this - &ArgusComponentRegistry::s_ObserversComponents[0];
}

void ObserversComponent::DrawComponentDebug() const
{
#if !UE_BUILD_SHIPPING
	if (!ImGui::CollapsingHeader("ObserversComponent"))
	{
		return;
	}   
#endif //!UE_BUILD_SHIPPING
}

// Per observable logic
