// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ComponentDefinitions/SpawningComponent.h"
#include "ArgusComponentRegistry.h"

#if !UE_BUILD_SHIPPING
#include "imgui.h"
#endif //!UE_BUILD_SHIPPING

// Component shared functionality
uint16 SpawningComponent::GetOwningEntityId() const
{
	return this - &ArgusComponentRegistry::s_SpawningComponents[0];
}

void SpawningComponent::DrawComponentDebug() const
{
#if !UE_BUILD_SHIPPING
	if (!ImGui::CollapsingHeader("SpawningComponent"))
	{
		return;
	}

	if (ImGui::BeginTable("ComponentValues", 2, ImGuiTableFlags_NoSavedSettings))
	{
		ImGui::TableNextColumn();
		ImGui::Text("m_spawningRadius");
		ImGui::TableNextColumn();
		ImGui::Text("%f", m_spawningRadius);
		ImGui::TableNextColumn();
		ImGui::Text("m_maximumQueueSize");
		ImGui::TableNextColumn();
		ImGui::Text("%d", m_maximumQueueSize);
		ImGui::TableNextColumn();
		ImGui::Text("m_currentQueueSize");
		ImGui::TableNextColumn();
		ImGui::Text("%d", m_currentQueueSize);
		ImGui::EndTable();
	}
#endif //!UE_BUILD_SHIPPING
}

// Per observable logic
