// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ComponentDefinitions/TriggerComponent.h"
#include "ArgusEntity.h"
#include "ArgusLogging.h"
#include "ArgusMath.h"
#include "Serialization/Archive.h"

#if !UE_BUILD_SHIPPING
#include "ArgusStaticData.h"
#include "imgui.h"
#include "UObject/ReflectedTypeAccessors.h"
#endif //!UE_BUILD_SHIPPING

// Component shared functionality
uint16 TriggerComponent::GetOwningEntityId() const
{
	return this - &ArgusComponentRegistry::s_TriggerComponents[0];
}

void TriggerComponent::Reset()
{
	m_overlappingEntityIds.Reset();
	//m_extendsToFlyingPlane = false;
}

void TriggerComponent::Serialize(FArchive& archive)
{
	//archive << m_extendsToFlyingPlane;
}

void TriggerComponent::DrawComponentDebug() const
{
#if !UE_BUILD_SHIPPING
	if (!ImGui::CollapsingHeader("TriggerComponent"))
	{
		return;
	}

	if (ImGui::BeginTable("ComponentValues", 2, ImGuiTableFlags_NoSavedSettings | ImGuiTableFlags_BordersInner))
	{
		ImGui::TableNextColumn();
		ImGui::Text("m_overlappingEntityIds");
		ImGui::TableNextColumn();
		ImGui::Text("Array max is currently = %d", m_overlappingEntityIds.Max());
		if (m_overlappingEntityIds.IsEmpty())
		{
			ImGui::Text("Array is empty");
		}
		else
		{
			ImGui::Text("Size of array = %d", m_overlappingEntityIds.Num());
			ImGui::Indent();
			for (int32 i = 0; i < m_overlappingEntityIds.Num(); ++i)
			{
				if (i != 0) ImGui::Separator();
				ImGui::Text("%d", m_overlappingEntityIds[i]);
			}
			ImGui::Unindent();
		}
		ImGui::TableNextColumn();
		ImGui::Text("m_extendsToFlyingPlane");
		ImGui::TableNextColumn();
		//ImGui::Text(m_extendsToFlyingPlane ? "true" : "false");
		ImGui::EndTable();
	}
#endif //!UE_BUILD_SHIPPING
}

// Per observable logic
