// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ComponentDefinitions/TriggerComponent.h"
#include "ArgusEntity.h"
#include "ArgusLogging.h"
#include "ArgusMath.h"
#include "Serialization/Archive.h"

#if !UE_BUILD_SHIPPING
#include "ArgusStaticData.h"
#include "imgui.h"
#include "UObject/ReflectedTypeAccessors.h"
#endif //!UE_BUILD_SHIPPING

// Component shared functionality
uint16 TriggerComponent::GetOwningEntityId() const
{
	return this - &ArgusComponentRegistry::s_TriggerComponents[0];
}

void TriggerComponent::Reset()
{
	m_overlappingEntityIds.Reset();
	m_removalStagedEntityIds.Reset();
	m_triggerPlanarOverlaps = EFlightCapability::OnlyGrounded;
}

void TriggerComponent::Serialize(FArchive& archive)
{
	archive << m_triggerPlanarOverlaps;
}

void TriggerComponent::DrawComponentDebug() const
{
#if !UE_BUILD_SHIPPING
	if (!ImGui::CollapsingHeader("TriggerComponent"))
	{
		return;
	}

	if (ImGui::BeginTable("ComponentValues", 2, ImGuiTableFlags_NoSavedSettings | ImGuiTableFlags_BordersInner))
	{
		ImGui::TableNextColumn();
		ImGui::Text("m_overlappingEntityIds");
		ImGui::TableNextColumn();
		if (m_overlappingEntityIds.IsEmpty())
		{
			ImGui::Text("Set is empty");
		}
		else
		{
			ImGui::Text("Size of set = %d", m_overlappingEntityIds.Num());
			ImGui::Indent();
			for (const auto& element_m_overlappingEntityIds : m_overlappingEntityIds)
			{
				ImGui::Text("%d", element_m_overlappingEntityIds);
			}
			ImGui::Unindent();
		}
		ImGui::TableNextColumn();
		ImGui::Text("m_removalStagedEntityIds");
		ImGui::TableNextColumn();
		if (m_removalStagedEntityIds.IsEmpty())
		{
			ImGui::Text("Set is empty");
		}
		else
		{
			ImGui::Text("Size of set = %d", m_removalStagedEntityIds.Num());
			ImGui::Indent();
			for (const auto& element_m_removalStagedEntityIds : m_removalStagedEntityIds)
			{
				ImGui::Text("%d", element_m_removalStagedEntityIds);
			}
			ImGui::Unindent();
		}
		ImGui::TableNextColumn();
		ImGui::Text("m_triggerPlanarOverlaps");
		ImGui::TableNextColumn();
		const char* valueName_m_triggerPlanarOverlaps = ARGUS_FSTRING_TO_CHAR(StaticEnum<EFlightCapability>()->GetNameStringByValue(static_cast<uint8>(m_triggerPlanarOverlaps)));
		ImGui::Text(valueName_m_triggerPlanarOverlaps);
		ImGui::EndTable();
	}
#endif //!UE_BUILD_SHIPPING
}

// Per observable logic
