// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ComponentDefinitions/TriggerComponent.h"
#include "ArgusEntity.h"
#include "ArgusLogging.h"
#include "ArgusMath.h"
#include "Serialization/Archive.h"

#if !UE_BUILD_SHIPPING
#include "ArgusStaticData.h"
#include "imgui.h"
#include "UObject/ReflectedTypeAccessors.h"
#endif //!UE_BUILD_SHIPPING

// Component shared functionality
uint16 TriggerComponent::GetOwningEntityId() const
{
	return this - &ArgusComponentRegistry::s_TriggerComponents[0];
}

void TriggerComponent::Reset()
{
	m_overlappingEntityIds.Reset();
	m_entityIdsAddedThisFrame.Reset();
	m_entityIdsRemovedThisFrame.Reset();
	m_triggerPlanarOverlaps = EFlightCapability::OnlyGrounded;
}

void TriggerComponent::Serialize(FArchive& archive)
{
	archive << m_triggerPlanarOverlaps;
}

void TriggerComponent::DrawComponentDebug() const
{
#if !UE_BUILD_SHIPPING
	if (!ImGui::CollapsingHeader("TriggerComponent"))
	{
		return;
	}

	if (ImGui::BeginTable("ComponentValues", 2, ImGuiTableFlags_NoSavedSettings | ImGuiTableFlags_BordersInner))
	{
		ImGui::TableNextColumn();
		ImGui::Text("m_overlappingEntityIds");
		ImGui::TableNextColumn();
		ImGui::Text("Array max is currently = %d", m_overlappingEntityIds.Max());
		if (m_overlappingEntityIds.IsEmpty())
		{
			ImGui::Text("Array is empty");
		}
		else
		{
			ImGui::Text("Size of array = %d", m_overlappingEntityIds.Num());
			ImGui::Indent();
			for (int32 i = 0; i < m_overlappingEntityIds.Num(); ++i)
			{
				if (i != 0) ImGui::Separator();
				ImGui::Text("%d", m_overlappingEntityIds[i]);
			}
			ImGui::Unindent();
		}
		ImGui::TableNextColumn();
		ImGui::Text("m_entityIdsAddedThisFrame");
		ImGui::TableNextColumn();
		ImGui::Text("Array max is currently = %d", m_entityIdsAddedThisFrame.Max());
		if (m_entityIdsAddedThisFrame.IsEmpty())
		{
			ImGui::Text("Array is empty");
		}
		else
		{
			ImGui::Text("Size of array = %d", m_entityIdsAddedThisFrame.Num());
			ImGui::Indent();
			for (int32 i = 0; i < m_entityIdsAddedThisFrame.Num(); ++i)
			{
				if (i != 0) ImGui::Separator();
				ImGui::Text("%d", m_entityIdsAddedThisFrame[i]);
			}
			ImGui::Unindent();
		}
		ImGui::TableNextColumn();
		ImGui::Text("m_entityIdsRemovedThisFrame");
		ImGui::TableNextColumn();
		ImGui::Text("Array max is currently = %d", m_entityIdsRemovedThisFrame.Max());
		if (m_entityIdsRemovedThisFrame.IsEmpty())
		{
			ImGui::Text("Array is empty");
		}
		else
		{
			ImGui::Text("Size of array = %d", m_entityIdsRemovedThisFrame.Num());
			ImGui::Indent();
			for (int32 i = 0; i < m_entityIdsRemovedThisFrame.Num(); ++i)
			{
				if (i != 0) ImGui::Separator();
				ImGui::Text("%d", m_entityIdsRemovedThisFrame[i]);
			}
			ImGui::Unindent();
		}
		ImGui::TableNextColumn();
		ImGui::Text("m_triggerPlanarOverlaps");
		ImGui::TableNextColumn();
		const char* valueName_m_triggerPlanarOverlaps = ARGUS_FSTRING_TO_CHAR(StaticEnum<EFlightCapability>()->GetNameStringByValue(static_cast<uint8>(m_triggerPlanarOverlaps)));
		ImGui::Text(valueName_m_triggerPlanarOverlaps);
		ImGui::EndTable();
	}
#endif //!UE_BUILD_SHIPPING
}

// Per observable logic
