// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ComponentDefinitions/VelocityComponent.h"
#include "ArgusEntity.h"

#if !UE_BUILD_SHIPPING
#include "ArgusStaticData.h"
#include "imgui.h"
#include "UObject/ReflectedTypeAccessors.h"
#endif //!UE_BUILD_SHIPPING

// Component shared functionality
uint16 VelocityComponent::GetOwningEntityId() const
{
	return this - &ArgusComponentRegistry::s_VelocityComponents[0];
}

void VelocityComponent::DrawComponentDebug() const
{
#if !UE_BUILD_SHIPPING
	if (!ImGui::CollapsingHeader("VelocityComponent"))
	{
		return;
	}

	if (ImGui::BeginTable("ComponentValues", 2, ImGuiTableFlags_NoSavedSettings))
	{
		ImGui::TableNextColumn();
		ImGui::Text("m_currentVelocity");
		ImGui::TableNextColumn();
		ImGui::Text("(%.2f, %.2f, %.2f)", m_currentVelocity.X, m_currentVelocity.Y, m_currentVelocity.Z);
		ImGui::TableNextColumn();
		ImGui::Text("m_proposedAvoidanceVelocity");
		ImGui::TableNextColumn();
		ImGui::Text("(%.2f, %.2f, %.2f)", m_proposedAvoidanceVelocity.X, m_proposedAvoidanceVelocity.Y, m_proposedAvoidanceVelocity.Z);
		ImGui::TableNextColumn();
		ImGui::Text("m_desiredSpeedUnitsPerSecond");
		ImGui::TableNextColumn();
		ImGui::Text("%.2f", m_desiredSpeedUnitsPerSecond);
		ImGui::EndTable();
	}
#endif //!UE_BUILD_SHIPPING
}

// Per observable logic
