// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ComponentDefinitions/WorldCellComponent.h"
#include "ArgusEntity.h"
#include "ArgusLogging.h"
#include "ArgusMath.h"
#include "Serialization/Archive.h"

#if !UE_BUILD_SHIPPING
#include "ArgusStaticData.h"
#include "imgui.h"
#include "UObject/ReflectedTypeAccessors.h"
#endif //!UE_BUILD_SHIPPING

// Component shared functionality
uint16 WorldCellComponent::GetOwningEntityId() const
{
	return this - &ArgusComponentRegistry::s_WorldCellComponents[0];
}

void WorldCellComponent::Reset()
{
	m_cellXCoordinate = 0;
	m_cellYCoordinate = 0;
}

void WorldCellComponent::Serialize(FArchive& archive)
{
	archive << m_cellXCoordinate;
	archive << m_cellYCoordinate;
}

void WorldCellComponent::DrawComponentDebug() const
{
#if !UE_BUILD_SHIPPING
	if (!ImGui::CollapsingHeader("WorldCellComponent"))
	{
		return;
	}

	if (ImGui::BeginTable("ComponentValues", 2, ImGuiTableFlags_NoSavedSettings | ImGuiTableFlags_BordersInner))
	{
		ImGui::TableNextColumn();
		ImGui::Text("m_cellXCoordinate");
		ImGui::TableNextColumn();
		ImGui::Text("%d", m_cellXCoordinate);
		ImGui::TableNextColumn();
		ImGui::Text("m_cellYCoordinate");
		ImGui::TableNextColumn();
		ImGui::Text("%d", m_cellYCoordinate);
		ImGui::EndTable();
	}
#endif //!UE_BUILD_SHIPPING
}

// Per observable logic
