// Copyright Karazaa. This is a part of an RTS project called Argus.

#include "ArgusCodeGenerator.h"
#include "ArgusCodeGeneratorStyle.h"
#include "ArgusCodeGeneratorCommands.h"
#include "ArgusComponentRegistryCodeGenerator.h"
#include "ArgusDataAssetComponentCodeGenerator.h"
#include "ArgusECSComponentAdder.h"
#include "ArgusStaticDataCodeGenerator.h"
#include "ArgusSystemArgsImplementationCodeGenerator.h"
#include "ComponentImplementationCodeGenerator.h"
#include "ComponentObserversCodeGenerator.h"
#include "Framework/Docking/TabManager.h"
#include "Misc/MessageDialog.h"
#include "ToolMenus.h"

static const FName ArgusCodeGeneratorTabName("Add Components");

#define LOCTEXT_NAMESPACE "FArgusCodeGeneratorModule"

#pragma region Plugin Methods
void FArgusCodeGeneratorModule::StartupModule()
{
	// This code will execute after your module is loaded into memory; the exact timing is specified in the .uplugin file per-module
	
	FArgusCodeGeneratorStyle::Initialize();
	FArgusCodeGeneratorStyle::ReloadTextures();

	FArgusCodeGeneratorCommands::Register();
	
	PluginCommands = MakeShareable(new FUICommandList);
	m_ecsTypeAdder = MakeShareable(new ArgusECSComponentAdder);

	PluginCommands->MapAction(
		FArgusCodeGeneratorCommands::Get().GenerateCode,
		FExecuteAction::CreateRaw(this, &FArgusCodeGeneratorModule::GenerateCode),
		FCanExecuteAction());

	PluginCommands->MapAction(
		FArgusCodeGeneratorCommands::Get().AddComponent,
		FExecuteAction::CreateRaw(this, &FArgusCodeGeneratorModule::AddComponent),
		FCanExecuteAction());

	UToolMenus::RegisterStartupCallback(FSimpleMulticastDelegate::FDelegate::CreateRaw(this, &FArgusCodeGeneratorModule::RegisterMenus));

	FGlobalTabmanager::Get()->RegisterNomadTabSpawner(ArgusCodeGeneratorTabName, FOnSpawnTab::CreateRaw(this, &FArgusCodeGeneratorModule::OnSpawnPluginTab))
		.SetDisplayName(LOCTEXT("FArgusCodeGeneratorTabTitle", "Add Components"))
		.SetMenuType(ETabSpawnerMenuType::Hidden);
}

void FArgusCodeGeneratorModule::ShutdownModule()
{
	// This function may be called during shutdown to clean up your module.  For modules that support dynamic reloading,
	// we call this function before unloading the module.

	UToolMenus::UnRegisterStartupCallback(this);

	UToolMenus::UnregisterOwner(this);

	FArgusCodeGeneratorStyle::Shutdown();

	FArgusCodeGeneratorCommands::Unregister();

	FGlobalTabmanager::Get()->UnregisterNomadTabSpawner(ArgusCodeGeneratorTabName);
}

void FArgusCodeGeneratorModule::RegisterMenus()
{
	// Owner will be used for cleanup in call to UToolMenus::UnregisterOwner
	FToolMenuOwnerScoped OwnerScoped(this);

	{
		UToolMenu* Menu = UToolMenus::Get()->ExtendMenu("LevelEditor.MainMenu.Window");
		{
			FToolMenuSection& Section = Menu->FindOrAddSection("WindowLayout");
			{
				FToolMenuEntry& Entry = Section.AddEntry(FToolMenuEntry::InitMenuEntry(FArgusCodeGeneratorCommands::Get().GenerateCode));
				FToolMenuEntry& SecondEntry = Section.AddEntry(FToolMenuEntry::InitMenuEntry(FArgusCodeGeneratorCommands::Get().AddComponent));
				Entry.SetCommandList(PluginCommands);
				SecondEntry.SetCommandList(PluginCommands);
			}
		}
	}

	{
		UToolMenu* ToolbarMenu = UToolMenus::Get()->ExtendMenu("LevelEditor.LevelEditorToolBar.PlayToolBar");
		{
			FToolMenuSection& Section = ToolbarMenu->FindOrAddSection("PluginTools");
			{
				FToolMenuEntry& Entry = Section.AddEntry(FToolMenuEntry::InitToolBarButton(FArgusCodeGeneratorCommands::Get().GenerateCode));
				FToolMenuEntry& SecondEntry = Section.AddEntry(FToolMenuEntry::InitToolBarButton(FArgusCodeGeneratorCommands::Get().AddComponent));
				Entry.SetCommandList(PluginCommands);
				SecondEntry.SetCommandList(PluginCommands);
			}
		}
	}
}
#pragma endregion

void FArgusCodeGeneratorModule::GenerateCode()
{
	ArgusCodeGeneratorUtil::ParseComponentDataOutput parsedComponentData;
	ArgusCodeGeneratorUtil::ParseStaticDataRecordsOutput parsedStaticDataRecords;
	ArgusCodeGeneratorUtil::ParseSystemArgDefinitionsOutput parsedSystemArgDefinitions;

	// Parse from source files
	ArgusCodeGeneratorUtil::ParseComponentData(parsedComponentData);
	ArgusCodeGeneratorUtil::ParseStaticDataRecords(parsedStaticDataRecords);
	ArgusCodeGeneratorUtil::ParseSystemArgDefinitions(parsedSystemArgDefinitions);

	// Write out autogenerated files
	ArgusComponentRegistryCodeGenerator::GenerateComponentRegistryCode(parsedComponentData);
	ArgusDataAssetComponentCodeGenerator::GenerateDataAssetComponentsCode(parsedComponentData);
	ComponentImplementationGenerator::GenerateComponentImplementationCode(parsedComponentData);
	ComponentObserversGenerator::GenerateComponentObserversCode(parsedComponentData);
	ArgusStaticDataCodeGenerator::GenerateStaticDataCode(parsedStaticDataRecords);
	ArgusSystemArgsImplementationCodeGenerator::GenerateSystemArgsImplementation(parsedSystemArgDefinitions);
}

void FArgusCodeGeneratorModule::AddComponent()
{
	FGlobalTabmanager::Get()->TryInvokeTab(ArgusCodeGeneratorTabName);
}

TSharedRef<SDockTab> FArgusCodeGeneratorModule::OnSpawnPluginTab(const FSpawnTabArgs& spawnTabArgs)
{
	return m_ecsTypeAdder->OnSpawnPluginTab(spawnTabArgs);
}

#undef LOCTEXT_NAMESPACE
	
IMPLEMENT_MODULE(FArgusCodeGeneratorModule, ArgusCodeGenerator)