// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ArgusStaticRecordReference.h"
#include "RecordDefinitions\AbilityRecord.h"
#include "AbilityRecordReference.generated.h"

USTRUCT()
struct FUAbilityRecordReference : public FArgusStaticRecordReference
{
	GENERATED_BODY();

public:
#if WITH_EDITOR
	void StoreId() const override;
#endif

private:
	UPROPERTY(EditAnywhere)
	TSoftObjectPtr<UAbilityRecord> m_softObjectPtr = nullptr;
};
