// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "RecordReferences/PersistentWorldTranslationRecordReference.h"
#include "RecordDefinitions/PersistentWorldTranslationRecord.h"
#include "ArgusLogging.h"

#if WITH_EDITOR && WITH_EDITORONLY_DATA
void FUPersistentWorldTranslationRecordReference::StoreId() const
{
	if (m_softObjectPtr.IsNull())
	{
		m_id = 0;
		return;
	}

	if (const UPersistentWorldTranslationRecord* record = m_softObjectPtr.LoadSynchronous())
	{
		m_id = record->m_id;
	}
	else
	{
		ARGUS_ERROR_NULL(ArgusStaticDataLog, record);
	}
}
#endif
