// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ArgusStaticRecordReference.h"
#include "ResourceSetRecordReference.generated.h"

class UResourceSetRecord;

USTRUCT()
struct FUResourceSetRecordReference : public FArgusStaticRecordReference
{
	GENERATED_BODY();

public:
#if WITH_EDITOR && WITH_EDITORONLY_DATA
	void StoreId() const override;
#endif

private:
#if WITH_EDITORONLY_DATA
	UPROPERTY(EditAnywhere)
	TSoftObjectPtr<UResourceSetRecord> m_softObjectPtr = nullptr;
#endif
};
