// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ArgusStaticRecordReference.h"
#include "RecordDefinitions\TeamColorRecord.h"
#include "TeamColorRecordReference.generated.h"

USTRUCT()
struct FUTeamColorRecordReference : public FArgusStaticRecordReference
{
	GENERATED_BODY();

public:
#if WITH_EDITOR
	void StoreId() const override;
#endif

private:
	UPROPERTY(EditAnywhere)
	TSoftObjectPtr<UTeamColorRecord> m_softObjectPtr = nullptr;
};
