// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "AbilityComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UAbilityComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	AbilityComponent* AbilityComponentRef = entity.GetOrAddComponent<AbilityComponent>();
	ARGUS_RETURN_ON_NULL(AbilityComponentRef, ArgusECSLog);

	AbilityComponentRef->m_ability0Id = m_ability0IdReference.GetId();
	AbilityComponentRef->m_ability1Id = m_ability1IdReference.GetId();
	AbilityComponentRef->m_ability2Id = m_ability2IdReference.GetId();
	AbilityComponentRef->m_ability3Id = m_ability3IdReference.GetId();
	AbilityComponentRef->m_abilityCasterPriority = m_abilityCasterPriority;
}

void UAbilityComponentData::OnComponentDataLoaded() const
{
	ArgusStaticData::AsyncPreLoadRecord<UAbilityRecord>(m_ability0IdReference.GetId());
	ArgusStaticData::AsyncPreLoadRecord<UAbilityRecord>(m_ability1IdReference.GetId());
	ArgusStaticData::AsyncPreLoadRecord<UAbilityRecord>(m_ability2IdReference.GetId());
	ArgusStaticData::AsyncPreLoadRecord<UAbilityRecord>(m_ability3IdReference.GetId());
}

bool UAbilityComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UAbilityComponentData>();
}
