// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ArgusDecalComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UArgusDecalComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	ArgusDecalComponent* ArgusDecalComponentRef = entity.GetOrAddComponent<ArgusDecalComponent>();
	ARGUS_RETURN_ON_NULL(ArgusDecalComponentRef, ArgusECSLog);

	ArgusDecalComponentRef->m_lifetimeSeconds = m_lifetimeSeconds;
}

void UArgusDecalComponentData::OnComponentDataLoaded() const
{
}

bool UArgusDecalComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UArgusDecalComponentData>();
}
