// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "AssetLoadingComponentData.generated.h"

UCLASS()
class ARGUS_API UAssetLoadingComponentData : public UComponentData
{
	GENERATED_BODY()

public:

	void InstantiateComponentForEntity(ArgusEntity entity) const override;
	bool MatchesType(UComponentData* other) const override;
};
