// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "AvoidanceGroupingComponentData.generated.h"

UCLASS()
class ARGUS_API UAvoidanceGroupingComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere)
	EAvoidancePriority m_avoidancePriority = EAvoidancePriority::Lowest;

	void InstantiateComponentForEntity(const ArgusEntity& entity) const override;
	bool MatchesType(UComponentData* other) const override;
};
