// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "AvoidanceGroupingComponentData.generated.h"

UCLASS()
class ARGUS_API UAvoidanceGroupingComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	TArray<uint16> m_adjacentEntities;
	FVector m_groupAverageLocation = FVector::ZeroVector;
	uint16 m_groupId = ArgusECSConstants::k_maxEntities;

	void InstantiateComponentForEntity(ArgusEntity& entity) const override;
	bool MatchesType(UComponentData* other) const override;
};
