// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "AvoidanceGroupingComponentData.generated.h"

UCLASS()
class ARGUS_API UAvoidanceGroupingComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere)
	EAvoidancePriority m_avoidancePriority = EAvoidancePriority::Lowest;


	void InstantiateComponentForEntity(ArgusEntity entity) const override;
	void OnComponentDataLoaded() const override;
	bool MatchesType(const UComponentData* other) const override;
};
