// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "CarrierComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UCarrierComponentData::InstantiateComponentForEntity(const ArgusEntity& entity) const
{
	CarrierComponent* CarrierComponentRef = entity.GetOrAddComponent<CarrierComponent>();
	ARGUS_RETURN_ON_NULL(CarrierComponentRef, ArgusECSLog);

	CarrierComponentRef->m_carrierCapacity = m_carrierCapacity;
}

bool UCarrierComponentData::MatchesType(UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	const UCarrierComponentData* otherComponentData = Cast<UCarrierComponentData>(other);
	if (!otherComponentData)
	{
		return false;
	}

	return true;
}
