// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "CombatComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UCombatComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	CombatComponent* CombatComponentRef = entity.GetOrAddComponent<CombatComponent>();
	ARGUS_RETURN_ON_NULL(CombatComponentRef, ArgusECSLog);

	CombatComponentRef->m_baseDamagePerIntervalOrPerSecond = m_baseDamagePerIntervalOrPerSecond;
	CombatComponentRef->m_intervalDurationSeconds = m_intervalDurationSeconds;
	CombatComponentRef->m_attackType = m_attackType;
	CombatComponentRef->m_rangedAttackCapability = m_rangedAttackCapability;
}

void UCombatComponentData::OnComponentDataLoaded() const
{
}

bool UCombatComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UCombatComponentData>();
}
