// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "CombatComponentData.h"
#include "ArgusStaticData.h"

void UCombatComponentData::InstantiateComponentForEntity(ArgusEntity& entity) const
{
	CombatComponent* CombatComponentRef = entity.AddComponent<CombatComponent>();
	CombatComponentRef->m_baseDamagePerIntervalOrPerSecond = m_baseDamagePerIntervalOrPerSecond;
	CombatComponentRef->m_intervalDurationSeconds = m_intervalDurationSeconds;
	CombatComponentRef->m_attackType = m_attackType;
	CombatComponentRef->m_attackTimerHandle = m_attackTimerHandle;
}

bool UCombatComponentData::MatchesType(UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	const UCombatComponentData* otherComponentData = Cast<UCombatComponentData>(other);
	if (!otherComponentData)
	{
		return false;
	}

	return true;
}
