// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ConstructionComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UConstructionComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	ConstructionComponent* ConstructionComponentRef = entity.GetOrAddComponent<ConstructionComponent>();
	ARGUS_RETURN_ON_NULL(ConstructionComponentRef, ArgusECSLog);

	ConstructionComponentRef->m_requiredWorkSeconds = m_requiredWorkSeconds;
	ConstructionComponentRef->m_currentWorkSeconds = m_currentWorkSeconds;
	if (const UArgusStaticRecord* record = m_constructionAbilityRecordId.LoadSynchronous())
	{
		m_constructionAbilityRecordIdLoaded = record->m_id;
	}
	ConstructionComponentRef->m_constructionAbilityRecordId = m_constructionAbilityRecordIdLoaded;
	ConstructionComponentRef->m_constructionType = m_constructionType;
}

void UConstructionComponentData::OnComponentDataLoaded() const
{
}

bool UConstructionComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UConstructionComponentData>();
}
