// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "ConstructionComponentData.generated.h"

UCLASS()
class ARGUS_API UConstructionComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere)
	float m_requiredWorkSeconds = 0.0f;
	UPROPERTY(EditAnywhere)
	EConstructionType m_constructionType = EConstructionType::Automatic;

	void InstantiateComponentForEntity(ArgusEntity& entity) const override;
	bool MatchesType(UComponentData* other) const override;
};
