// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "DecalSystemsSettingsComponentData.generated.h"

UCLASS()
class ARGUS_API UDecalSystemsSettingsComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere)
	FUMaterialRecordReference m_moveToLocationDecalMaterial;

	UPROPERTY(EditAnywhere)
	FUMaterialRecordReference m_attackMoveToLocationDecalMaterial;


	void InstantiateComponentForEntity(ArgusEntity entity) const override;
	void OnComponentDataLoaded() const override;
	bool MatchesType(const UComponentData* other) const override;
};
