// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "EffortCoefficientSettingsComponentData.generated.h"

UCLASS()
class ARGUS_API UEffortCoefficientSettingsComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, meta = (Category = "Same Avoidance Group")) 
	float m_sameAvoidanceGroupBase = 0.5f;

	UPROPERTY(EditAnywhere, meta = (Category = "Same Avoidance Group")) 
	float m_sameAvoidanceGroupBothObstacle = 0.3f;

	UPROPERTY(EditAnywhere, meta = (Category = "Same Avoidance Group")) 
	float m_sameAvoidanceGroupHasObstacle = 0.0f;

	UPROPERTY(EditAnywhere, meta = (Category = "Same Avoidance Group")) 
	float m_sameAvoidanceGroupOtherHasObstacle = 0.75f;


	void InstantiateComponentForEntity(ArgusEntity entity) const override;
	void OnComponentDataLoaded() const override;
	bool MatchesType(const UComponentData* other) const override;
};
