// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "EffortCoefficientSettingsComponentData.generated.h"

UCLASS()
class ARGUS_API UEffortCoefficientSettingsComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, meta = (Category = "Same Avoidance Group")) 
	float m_sameAvoidanceGroupBase = 0.5f;

	UPROPERTY(EditAnywhere, meta = (Category = "Same Avoidance Group")) 
	float m_sameAvoidanceGroupIsAttacking = 0.33f;

	UPROPERTY(EditAnywhere, meta = (Category = "Same Avoidance Group")) 
	float m_sameAvoidanceGroupIsConstructing = 0.33f;

	UPROPERTY(EditAnywhere, meta = (Category = "Adjacent to Obstacles")) 
	float m_sameTeamBothObstacle = 0.4f;

	UPROPERTY(EditAnywhere, meta = (Category = "Adjacent to Obstacles")) 
	float m_sameTeamHasObstacle = 0.0f;

	UPROPERTY(EditAnywhere, meta = (Category = "Adjacent to Obstacles")) 
	float m_sameTeamOtherHasObstacle = 1.0f;


	void InstantiateComponentForEntity(ArgusEntity entity) const override;
	void ReinitializeComponentForEntityPostLoad(ArgusEntity entity) const override;
	void OnComponentDataLoaded() const override;
	bool MatchesType(const UComponentData* other) const override;
};
