// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "EffortCoefficientSettingsComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UEffortCoefficientSettingsComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	EffortCoefficientSettingsComponent* EffortCoefficientSettingsComponentRef = entity.GetOrAddComponent<EffortCoefficientSettingsComponent>();
	ARGUS_RETURN_ON_NULL(EffortCoefficientSettingsComponentRef, ArgusECSLog);

	EffortCoefficientSettingsComponentRef->m_sameAvoidanceGroupBase = m_sameAvoidanceGroupBase;
	EffortCoefficientSettingsComponentRef->m_sameAvoidanceGroupIsAttacking = m_sameAvoidanceGroupIsAttacking;
	EffortCoefficientSettingsComponentRef->m_sameAvoidanceGroupIsConstructing = m_sameAvoidanceGroupIsConstructing;
	EffortCoefficientSettingsComponentRef->m_sameTeamBothObstacle = m_sameTeamBothObstacle;
	EffortCoefficientSettingsComponentRef->m_sameTeamHasObstacle = m_sameTeamHasObstacle;
	EffortCoefficientSettingsComponentRef->m_sameTeamOtherHasObstacle = m_sameTeamOtherHasObstacle;
}

void UEffortCoefficientSettingsComponentData::ReinitializeComponentForEntityPostLoad(ArgusEntity entity) const
{
	EffortCoefficientSettingsComponent* EffortCoefficientSettingsComponentRef = entity.GetComponent<EffortCoefficientSettingsComponent>();
	ARGUS_RETURN_ON_NULL(EffortCoefficientSettingsComponentRef, ArgusECSLog);

	EffortCoefficientSettingsComponentRef->m_sameAvoidanceGroupBase = m_sameAvoidanceGroupBase;
	EffortCoefficientSettingsComponentRef->m_sameAvoidanceGroupIsAttacking = m_sameAvoidanceGroupIsAttacking;
	EffortCoefficientSettingsComponentRef->m_sameAvoidanceGroupIsConstructing = m_sameAvoidanceGroupIsConstructing;
	EffortCoefficientSettingsComponentRef->m_sameTeamBothObstacle = m_sameTeamBothObstacle;
	EffortCoefficientSettingsComponentRef->m_sameTeamHasObstacle = m_sameTeamHasObstacle;
	EffortCoefficientSettingsComponentRef->m_sameTeamOtherHasObstacle = m_sameTeamOtherHasObstacle;
}

void UEffortCoefficientSettingsComponentData::OnComponentDataLoaded() const
{
}

bool UEffortCoefficientSettingsComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UEffortCoefficientSettingsComponentData>();
}
