// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "FacingComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UFacingComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	FacingComponent* FacingComponentRef = entity.GetOrAddComponent<FacingComponent>();
	ARGUS_RETURN_ON_NULL(FacingComponentRef, ArgusECSLog);

	FacingComponentRef->m_smoothedYaw = ArgusMath::ExponentialDecaySmoother<float>(m_smoothedYawDecayConstant, m_smoothedYawSmoothingSpeedMod);
}

void UFacingComponentData::ReinitializeComponentForEntityPostLoad(ArgusEntity entity) const
{
	FacingComponent* FacingComponentRef = entity.GetComponent<FacingComponent>();
	ARGUS_RETURN_ON_NULL(FacingComponentRef, ArgusECSLog);

}

void UFacingComponentData::OnComponentDataLoaded() const
{
}

bool UFacingComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UFacingComponentData>();
}
