// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "FacingComponentData.generated.h"

UCLASS()
class ARGUS_API UFacingComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere)
	float m_smoothedFacingFrequency = 1.0f;

	UPROPERTY(EditAnywhere)
	float m_smoothedFacingDamping = 1.0f;

	UPROPERTY(EditAnywhere)
	float m_smoothedFacingResponse = 0.0f;


	void InstantiateComponentForEntity(ArgusEntity entity) const override;
	void ReinitializeComponentForEntityPostLoad(ArgusEntity entity) const override;
	void OnComponentDataLoaded() const override;
	bool MatchesType(const UComponentData* other) const override;
};
