// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "FlightTransitionComponentData.generated.h"

UCLASS()
class ARGUS_API UFlightTransitionComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere)
	float m_smoothedTransitionAltitudeFrequency = 1.0f;

	UPROPERTY(EditAnywhere)
	float m_smoothedTransitionAltitudeDamping = 1.0f;

	UPROPERTY(EditAnywhere)
	float m_smoothedTransitionAltitudeResponse = 0.0f;


	void InstantiateComponentForEntity(ArgusEntity entity) const override;
	void ReinitializeComponentForEntityPostLoad(ArgusEntity entity) const override;
	void OnComponentDataLoaded() const override;
	bool MatchesType(const UComponentData* other) const override;
};
