// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "FlockingComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UFlockingComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	FlockingComponent* FlockingComponentRef = entity.GetOrAddComponent<FlockingComponent>();
	ARGUS_RETURN_ON_NULL(FlockingComponentRef, ArgusECSLog);

	FlockingComponentRef->m_maxShrinkingDurationTimeoutSeconds = m_maxShrinkingDurationTimeoutSeconds;
	FlockingComponentRef->m_flockingRootRadiusIncrement = m_flockingRootRadiusIncrement;
}

void UFlockingComponentData::OnComponentDataLoaded() const
{
}

bool UFlockingComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UFlockingComponentData>();
}
