// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "FogOfWarComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UFogOfWarComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	FogOfWarComponent* FogOfWarComponentRef = entity.GetOrAddComponent<FogOfWarComponent>();
	ARGUS_RETURN_ON_NULL(FogOfWarComponentRef, ArgusECSLog);

	FogOfWarComponentRef->m_fogOfWarTexture = m_fogOfWarTexture;
	FogOfWarComponentRef->m_gaussianWeightsTexture = m_gaussianWeightsTexture;
	FogOfWarComponentRef->m_dynamicMaterialInstance = m_dynamicMaterialInstance;
	FogOfWarComponentRef->m_gaussianDimension = m_gaussianDimension;
	FogOfWarComponentRef->m_revealedOnceAlpha = m_revealedOnceAlpha;
	FogOfWarComponentRef->m_textureSize = m_textureSize;
	FogOfWarComponentRef->m_smoothingDecayConstant = m_smoothingDecayConstant;
	FogOfWarComponentRef->m_shouldUseSmoothing = m_shouldUseSmoothing;
	FogOfWarComponentRef->m_triangleRasterizeModulo = m_triangleRasterizeModulo;
	FogOfWarComponentRef->m_numberSmoothingChunks = m_numberSmoothingChunks;
	FogOfWarComponentRef->m_visionObstacleAdjustDistance = m_visionObstacleAdjustDistance;
}

void UFogOfWarComponentData::OnComponentDataLoaded() const
{
}

bool UFogOfWarComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UFogOfWarComponentData>();
}
