// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "HealthComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UHealthComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	HealthComponent* HealthComponentRef = entity.GetOrAddComponent<HealthComponent>();
	ARGUS_RETURN_ON_NULL(HealthComponentRef, ArgusECSLog);

	HealthComponentRef->m_currentHealth = m_currentHealth;
	HealthComponentRef->m_maximumHealth = m_maximumHealth;
}

bool UHealthComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UHealthComponentData>();
}
