// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "HealthComponentData.h"

void UHealthComponentData::InstantiateComponentForEntity(ArgusEntity& entity) const
{
	HealthComponent* HealthComponentRef = entity.AddComponent<HealthComponent>();
	HealthComponentRef->m_health = m_health;
}

bool UHealthComponentData::MatchesType(UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	const UHealthComponentData* otherComponentData = Cast<UHealthComponentData>(other);
	if (!otherComponentData)
	{
		return false;
	}

	return true;
}
