// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "IdentityComponentData.generated.h"

UCLASS()
class ARGUS_API UIdentityComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere)
	TSoftObjectPtr<UFactionRecord> m_factionId;
private:
	mutable uint32 m_factionIdLoaded = 0u;
public:
	uint32 Get_m_factionId() const { return m_factionIdLoaded; }


	void InstantiateComponentForEntity(ArgusEntity entity) const override;
	void OnComponentDataLoaded() const override;
	bool MatchesType(const UComponentData* other) const override;
};
