// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "IdentityComponentData.generated.h"

UCLASS()
class ARGUS_API UIdentityComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere)
	ETeam m_team = ETeam::None;
	UPROPERTY(EditAnywhere, meta = (Bitmask, BitmaskEnum = ETeam))
	uint8 m_allies = 0u;
	UPROPERTY(EditAnywhere, meta = (Bitmask, BitmaskEnum = ETeam))
	uint8 m_enemies = 0u;

	void InstantiateComponentForEntity(ArgusEntity& entity) const override;
	bool MatchesType(UComponentData* other) const override;
};
