// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "NavigationComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UNavigationComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	NavigationComponent* NavigationComponentRef = entity.GetOrAddComponent<NavigationComponent>();
	ARGUS_RETURN_ON_NULL(NavigationComponentRef, ArgusECSLog);

}

void UNavigationComponentData::OnComponentDataLoaded() const
{
}

bool UNavigationComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UNavigationComponentData>();
}
