// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "NearbyEntitiesComponentData.h"
#include "ArgusStaticData.h"

void UNearbyEntitiesComponentData::InstantiateComponentForEntity(ArgusEntity& entity) const
{
	NearbyEntitiesComponent* NearbyEntitiesComponentRef = entity.AddComponent<NearbyEntitiesComponent>();
	NearbyEntitiesComponentRef->m_nearbyEntities = m_nearbyEntities;
}

bool UNearbyEntitiesComponentData::MatchesType(UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	const UNearbyEntitiesComponentData* otherComponentData = Cast<UNearbyEntitiesComponentData>(other);
	if (!otherComponentData)
	{
		return false;
	}

	return true;
}
