// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "NearbyObstaclesComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UNearbyObstaclesComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	NearbyObstaclesComponent* NearbyObstaclesComponentRef = entity.GetOrAddComponent<NearbyObstaclesComponent>();
	ARGUS_RETURN_ON_NULL(NearbyObstaclesComponentRef, ArgusECSLog);

}

bool UNearbyObstaclesComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UNearbyObstaclesComponentData>();
}
