// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "NearbyEntitiesComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UNearbyEntitiesComponentData::InstantiateComponentForEntity(const ArgusEntity& entity) const
{
	NearbyEntitiesComponent* NearbyEntitiesComponentRef = entity.GetOrAddComponent<NearbyEntitiesComponent>();
	ARGUS_RETURN_ON_NULL(NearbyEntitiesComponentRef, ArgusECSLog);

}

bool UNearbyEntitiesComponentData::MatchesType(UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	const UNearbyEntitiesComponentData* otherComponentData = Cast<UNearbyEntitiesComponentData>(other);
	if (!otherComponentData)
	{
		return false;
	}

	return true;
}
