// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ObserversComponentData.h"
#include "ArgusStaticData.h"

void UObserversComponentData::InstantiateComponentForEntity(ArgusEntity& entity) const
{
	ObserversComponent* ObserversComponentRef = entity.AddComponent<ObserversComponent>();
	ObserversComponentRef->m_PassengerComponentObservers = m_PassengerComponentObservers;
	ObserversComponentRef->m_TaskComponentObservers = m_TaskComponentObservers;
}

bool UObserversComponentData::MatchesType(UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	const UObserversComponentData* otherComponentData = Cast<UObserversComponentData>(other);
	if (!otherComponentData)
	{
		return false;
	}

	return true;
}
