// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "PassengerComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UPassengerComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	PassengerComponent* PassengerComponentRef = entity.GetOrAddComponent<PassengerComponent>();
	ARGUS_RETURN_ON_NULL(PassengerComponentRef, ArgusECSLog);

	PassengerComponentRef->m_carrierEntityId = m_carrierEntityId;
}

void UPassengerComponentData::OnComponentDataLoaded() const
{
}

bool UPassengerComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UPassengerComponentData>();
}
