// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "PassengerComponentData.generated.h"

UCLASS()
class ARGUS_API UPassengerComponentData : public UComponentData
{
	GENERATED_BODY()

public:

	void InstantiateComponentForEntity(ArgusEntity entity) const override;
	void OnComponentDataLoaded() const override;
	bool MatchesType(const UComponentData* other) const override;
};
