// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "RelativePolygonComponentData.generated.h"

UCLASS()
class ARGUS_API URelativePolygonComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere)
	TArray<FVector2D> m_relativeUnrealVerticies;

	UPROPERTY(EditAnywhere)
	ERelativePolygonType m_polygonType = ERelativePolygonType::TriggerVolume;


	void InstantiateComponentForEntity(ArgusEntity entity) const override;
	void ReinitializeComponentForEntityPostLoad(ArgusEntity entity) const override;
	void OnComponentDataLoaded() const override;
	bool MatchesType(const UComponentData* other) const override;
};
