// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "RelativeCircleComponentData.generated.h"

UCLASS()
class ARGUS_API URelativeCircleComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere)
	FVector2D m_relativeCenter = FVector2D::ZeroVector;

	UPROPERTY(EditAnywhere)
	float m_radius = 100.0f;


	void InstantiateComponentForEntity(ArgusEntity entity) const override;
	void ReinitializeComponentForEntityPostLoad(ArgusEntity entity) const override;
	void OnComponentDataLoaded() const override;
	bool MatchesType(const UComponentData* other) const override;
};
