// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "RelativeCircleComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void URelativeCircleComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	RelativeCircleComponent* RelativeCircleComponentRef = entity.GetOrAddComponent<RelativeCircleComponent>();
	ARGUS_RETURN_ON_NULL(RelativeCircleComponentRef, ArgusECSLog);

	RelativeCircleComponentRef->m_relativeCenter = m_relativeCenter;
	RelativeCircleComponentRef->m_radius = m_radius;
}

void URelativeCircleComponentData::ReinitializeComponentForEntityPostLoad(ArgusEntity entity) const
{
	RelativeCircleComponent* RelativeCircleComponentRef = entity.GetComponent<RelativeCircleComponent>();
	ARGUS_RETURN_ON_NULL(RelativeCircleComponentRef, ArgusECSLog);

}

void URelativeCircleComponentData::OnComponentDataLoaded() const
{
}

bool URelativeCircleComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<URelativeCircleComponentData>();
}
