// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ResourceExtractionComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UResourceExtractionComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	ResourceExtractionComponent* ResourceExtractionComponentRef = entity.GetOrAddComponent<ResourceExtractionComponent>();
	ARGUS_RETURN_ON_NULL(ResourceExtractionComponentRef, ArgusECSLog);

	ResourceExtractionComponentRef->m_resourcesToExtractRecordId = m_resourcesToExtractRecordId.LoadSynchronous() ? m_resourcesToExtractRecordId.LoadSynchronous()->m_id : 0u;
	ResourceExtractionComponentRef->m_extractionLengthSeconds = m_extractionLengthSeconds;
}

bool UResourceExtractionComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UResourceExtractionComponentData>();
}
