// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ResourceExtractionComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UResourceExtractionComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	ResourceExtractionComponent* ResourceExtractionComponentRef = entity.GetOrAddComponent<ResourceExtractionComponent>();
	ARGUS_RETURN_ON_NULL(ResourceExtractionComponentRef, ArgusECSLog);

	ResourceExtractionComponentRef->m_resourcesToExtractRecordId = m_resourcesToExtractRecordIdReference.GetId();
	ResourceExtractionComponentRef->m_extractionLengthSeconds = m_extractionLengthSeconds;
}

void UResourceExtractionComponentData::OnComponentDataLoaded() const
{
	ArgusStaticData::AsyncPreLoadRecord<UResourceSetRecord>(m_resourcesToExtractRecordIdReference.GetId());
}

bool UResourceExtractionComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UResourceExtractionComponentData>();
}
