// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ResourceExtractionComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UResourceExtractionComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	ResourceExtractionComponent* ResourceExtractionComponentRef = entity.GetOrAddComponent<ResourceExtractionComponent>();
	ARGUS_RETURN_ON_NULL(ResourceExtractionComponentRef, ArgusECSLog);

	if (const UArgusStaticRecord* record = m_resourcesToExtractRecordId.LoadSynchronous())
	{
		m_resourcesToExtractRecordIdLoaded = record->m_id;
	}
	ResourceExtractionComponentRef->m_resourcesToExtractRecordId = m_resourcesToExtractRecordIdLoaded;
	ResourceExtractionComponentRef->m_extractionLengthSeconds = m_extractionLengthSeconds;
}

void UResourceExtractionComponentData::OnComponentDataLoaded() const
{
}

bool UResourceExtractionComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UResourceExtractionComponentData>();
}
