// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ResourceComponentData.h"
#include "ArgusStaticData.h"

void UResourceComponentData::InstantiateComponentForEntity(ArgusEntity& entity) const
{
	ResourceComponent* ResourceComponentRef = entity.AddComponent<ResourceComponent>();
	ResourceComponentRef->m_resourceSet = m_resourceSet;
}

bool UResourceComponentData::MatchesType(UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	const UResourceComponentData* otherComponentData = Cast<UResourceComponentData>(other);
	if (!otherComponentData)
	{
		return false;
	}

	return true;
}
