// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "RecordReferences/ResourceSetRecordReference.h"
#include "ResourceExtractionComponentData.generated.h"

UCLASS()
class ARGUS_API UResourceExtractionComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere)
	FUResourceSetRecordReference m_resourcesToExtractRecordIdReference;

	UPROPERTY(EditAnywhere)
	float m_extractionLengthSeconds = 1.0f;


	void InstantiateComponentForEntity(ArgusEntity entity) const override;
	void OnComponentDataLoaded() const override;
	bool MatchesType(const UComponentData* other) const override;
};
