// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "ReticleComponentData.generated.h"

UCLASS()
class ARGUS_API UReticleComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	uint32 m_abilityRecordId = 0u;

	void InstantiateComponentForEntity(ArgusEntity& entity) const override;
	bool MatchesType(UComponentData* other) const override;
};
