// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "ReticleComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UReticleComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	ReticleComponent* ReticleComponentRef = entity.GetOrAddComponent<ReticleComponent>();
	ARGUS_RETURN_ON_NULL(ReticleComponentRef, ArgusECSLog);

}

bool UReticleComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UReticleComponentData>();
}
