// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "SpatialPartitioningComponentData.generated.h"

UCLASS()
class ARGUS_API USpatialPartitioningComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere)
	float m_validSpaceExtent = 3000.0f;
	UPROPERTY(EditAnywhere)
	float m_flyingPlaneHeight = 300.0f;
	UPROPERTY(EditAnywhere)
	float m_elevatedObstaclePointHeightThreshold = 10.0f;

	void InstantiateComponentForEntity(ArgusEntity entity) const override;
	bool MatchesType(UComponentData* other) const override;
};
