// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "SpatialPartitioningComponentData.generated.h"

UCLASS()
class ARGUS_API USpatialPartitioningComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	ArgusKDTree m_argusKDTree;

	void InstantiateComponentForEntity(ArgusEntity& entity) const override;
	bool MatchesType(UComponentData* other) const override;
};
