// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "SpawningComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void USpawningComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	SpawningComponent* SpawningComponentRef = entity.GetOrAddComponent<SpawningComponent>();
	ARGUS_RETURN_ON_NULL(SpawningComponentRef, ArgusECSLog);

	SpawningComponentRef->m_spawningRadius = m_spawningRadius;
	SpawningComponentRef->m_maximumQueueSize = m_maximumQueueSize;
}

bool USpawningComponentData::MatchesType(UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	const USpawningComponentData* otherComponentData = Cast<USpawningComponentData>(other);
	if (!otherComponentData)
	{
		return false;
	}

	return true;
}
