// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "SpawningComponentData.generated.h"

UCLASS()
class ARGUS_API USpawningComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere)
	TSoftObjectPtr<UArgusActorRecord> m_argusActorRecordId;
	UPROPERTY(EditAnywhere)
	float m_spawningRadius = 100.0f;
	UPROPERTY(EditAnywhere)
	uint8 m_maximumQueueSize = 10u;
	uint8 m_currentQueueSize = 0u;
	TimerHandle m_spawnTimerHandle;
	ArgusQueue<SpawnEntityInfo> m_spawnQueue;

	void InstantiateComponentForEntity(ArgusEntity& entity) const override;
	bool MatchesType(UComponentData* other) const override;
};
