// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "SpawningComponentData.generated.h"

UCLASS()
class ARGUS_API USpawningComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere)
	float m_spawningRadius = 100.0f;

	UPROPERTY(EditAnywhere)
	uint8 m_maximumQueueSize = 10u;


	void InstantiateComponentForEntity(ArgusEntity entity) const override;
	void OnComponentDataLoaded() const override;
	bool MatchesType(const UComponentData* other) const override;
};
