// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "TargetingComponentData.h"

void UTargetingComponentData::InstantiateComponentForEntity(ArgusEntity& entity) const
{
	TargetingComponent* TargetingComponentRef = entity.AddComponent<TargetingComponent>();
	TargetingComponentRef->m_targetEntityId = m_targetEntityId;
	TargetingComponentRef->m_targetLocation = m_targetLocation;
}

bool UTargetingComponentData::MatchesType(UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	const UTargetingComponentData* otherComponentData = Cast<UTargetingComponentData>(other);
	if (!otherComponentData)
	{
		return false;
	}

	return true;
}
