// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "TaskComponentData.generated.h"

UCLASS()
class ARGUS_API UTaskComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	EBaseState m_baseState = EBaseState::Alive;

	UPROPERTY(EditAnywhere)
	EFlightState m_flightState = EFlightState::Grounded;


	void InstantiateComponentForEntity(ArgusEntity entity) const override;
	void OnComponentDataLoaded() const override;
	bool MatchesType(const UComponentData* other) const override;
};
