// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "TaskComponentData.h"
#include "ArgusStaticData.h"

void UTaskComponentData::InstantiateComponentForEntity(ArgusEntity& entity) const
{
	TaskComponent* TaskComponentRef = entity.AddComponent<TaskComponent>();
	TaskComponentRef->m_currentTask = m_currentTask;
}

bool UTaskComponentData::MatchesType(UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	const UTaskComponentData* otherComponentData = Cast<UTaskComponentData>(other);
	if (!otherComponentData)
	{
		return false;
	}

	return true;
}
