// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "TaskComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UTaskComponentData::InstantiateComponentForEntity(const ArgusEntity& entity) const
{
	TaskComponent* TaskComponentRef = entity.GetOrAddComponent<TaskComponent>();
	ARGUS_RETURN_ON_NULL(TaskComponentRef, ArgusECSLog);

	TaskComponentRef->m_baseState = m_baseState;
}

bool UTaskComponentData::MatchesType(UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	const UTaskComponentData* otherComponentData = Cast<UTaskComponentData>(other);
	if (!otherComponentData)
	{
		return false;
	}

	return true;
}
