// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "TaskComponentData.h"
#include "ArgusStaticData.h"

void UTaskComponentData::InstantiateComponentForEntity(ArgusEntity& entity) const
{
	TaskComponent* TaskComponentRef = entity.AddComponent<TaskComponent>();
	TaskComponentRef->m_spawnedFromArgusActorRecordId = m_spawnedFromArgusActorRecordId;
	TaskComponentRef->m_baseState = m_baseState;
	TaskComponentRef->m_movementState = m_movementState;
	TaskComponentRef->m_spawningState = m_spawningState;
	TaskComponentRef->m_abilityState = m_abilityState;
	TaskComponentRef->m_constructionState = m_constructionState;
	TaskComponentRef->m_combatState = m_combatState;
	TaskComponentRef->m_resourceExtractionState = m_resourceExtractionState;
}

bool UTaskComponentData::MatchesType(UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	const UTaskComponentData* otherComponentData = Cast<UTaskComponentData>(other);
	if (!otherComponentData)
	{
		return false;
	}

	return true;
}
