// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "TeamCommanderComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UTeamCommanderComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	TeamCommanderComponent* TeamCommanderComponentRef = entity.GetOrAddComponent<TeamCommanderComponent>();
	ARGUS_RETURN_ON_NULL(TeamCommanderComponentRef, ArgusECSLog);

	TeamCommanderComponentRef->m_revealedAreaDimensionLength = m_revealedAreaDimensionLength;
}

bool UTeamCommanderComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UTeamCommanderComponentData>();
}
