// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "TeamCommanderComponentData.generated.h"

UCLASS()
class ARGUS_API UTeamCommanderComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere)
	float m_revealedAreaDimensionLength = 800.0f;

	UPROPERTY(EditAnywhere, meta = (Bitmask, BitmaskEnum = "/Script/Argus.ETeam"))
	uint8 m_allies = 0u;

	UPROPERTY(EditAnywhere, meta = (Bitmask, BitmaskEnum = "/Script/Argus.ETeam"))
	uint8 m_enemies = 0u;


	void InstantiateComponentForEntity(ArgusEntity entity) const override;
	void ReinitializeComponentForEntityPostLoad(ArgusEntity entity) const override;
	void OnComponentDataLoaded() const override;
	bool MatchesType(const UComponentData* other) const override;
};
