// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "TeamCommanderResourceDataComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UTeamCommanderResourceDataComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	TeamCommanderResourceDataComponent* TeamCommanderResourceDataComponentRef = entity.GetOrAddComponent<TeamCommanderResourceDataComponent>();
	ARGUS_RETURN_ON_NULL(TeamCommanderResourceDataComponentRef, ArgusECSLog);

}

void UTeamCommanderResourceDataComponentData::ReinitializeComponentForEntityPostLoad(ArgusEntity entity) const
{
	TeamCommanderResourceDataComponent* TeamCommanderResourceDataComponentRef = entity.GetComponent<TeamCommanderResourceDataComponent>();
	ARGUS_RETURN_ON_NULL(TeamCommanderResourceDataComponentRef, ArgusECSLog);

}

void UTeamCommanderResourceDataComponentData::OnComponentDataLoaded() const
{
}

bool UTeamCommanderResourceDataComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UTeamCommanderResourceDataComponentData>();
}
