// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "TeamCommanderComponentData.generated.h"

UCLASS()
class ARGUS_API UTeamCommanderComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere)
	float m_revealedAreaDimensionLength = 800.0f;

	void InstantiateComponentForEntity(ArgusEntity entity) const override;
	bool MatchesType(const UComponentData* other) const override;
};
