// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "TransformComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UTransformComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	TransformComponent* TransformComponentRef = entity.GetOrAddComponent<TransformComponent>();
	ARGUS_RETURN_ON_NULL(TransformComponentRef, ArgusECSLog);

	TransformComponentRef->m_radius = m_radius;
	TransformComponentRef->m_flightCapability = m_flightCapability;
}

void UTransformComponentData::ReinitializeComponentForEntityPostLoad(ArgusEntity entity) const
{
	TransformComponent* TransformComponentRef = entity.GetComponent<TransformComponent>();
	ARGUS_RETURN_ON_NULL(TransformComponentRef, ArgusECSLog);

}

void UTransformComponentData::OnComponentDataLoaded() const
{
}

bool UTransformComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UTransformComponentData>();
}
