// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ComponentData.h"
#include "TriggerComponentData.generated.h"

UCLASS()
class ARGUS_API UTriggerComponentData : public UComponentData
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere)
	bool m_extendsToFlyingPlane = false;


	void InstantiateComponentForEntity(ArgusEntity entity) const override;
	void ReinitializeComponentForEntityPostLoad(ArgusEntity entity) const override;
	void OnComponentDataLoaded() const override;
	bool MatchesType(const UComponentData* other) const override;
};
