// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "TriggerComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UTriggerComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	TriggerComponent* TriggerComponentRef = entity.GetOrAddComponent<TriggerComponent>();
	ARGUS_RETURN_ON_NULL(TriggerComponentRef, ArgusECSLog);

	// TriggerComponentRef->m_extendsToFlyingPlane = m_extendsToFlyingPlane;
}

void UTriggerComponentData::ReinitializeComponentForEntityPostLoad(ArgusEntity entity) const
{
	TriggerComponent* TriggerComponentRef = entity.GetComponent<TriggerComponent>();
	ARGUS_RETURN_ON_NULL(TriggerComponentRef, ArgusECSLog);

}

void UTriggerComponentData::OnComponentDataLoaded() const
{
}

bool UTriggerComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UTriggerComponentData>();
}
