// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "VelocityComponentData.h"
#include "ArgusStaticData.h"

void UVelocityComponentData::InstantiateComponentForEntity(ArgusEntity& entity) const
{
	VelocityComponent* VelocityComponentRef = entity.AddComponent<VelocityComponent>();
	VelocityComponentRef->m_currentVelocity = m_currentVelocity;
	VelocityComponentRef->m_proposedAvoidanceVelocity = m_proposedAvoidanceVelocity;
	VelocityComponentRef->m_desiredSpeedUnitsPerSecond = m_desiredSpeedUnitsPerSecond;
}

bool UVelocityComponentData::MatchesType(UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	const UVelocityComponentData* otherComponentData = Cast<UVelocityComponentData>(other);
	if (!otherComponentData)
	{
		return false;
	}

	return true;
}
