// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "VelocityComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UVelocityComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	VelocityComponent* VelocityComponentRef = entity.GetOrAddComponent<VelocityComponent>();
	ARGUS_RETURN_ON_NULL(VelocityComponentRef, ArgusECSLog);

	VelocityComponentRef->m_desiredSpeedUnitsPerSecond = m_desiredSpeedUnitsPerSecond;
	VelocityComponentRef->m_desiredFlightSpeedUnitsPerSecond = m_desiredFlightSpeedUnitsPerSecond;
}

bool UVelocityComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UVelocityComponentData>();
}
