// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "WorldCellComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UWorldCellComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	WorldCellComponent* WorldCellComponentRef = entity.GetOrAddComponent<WorldCellComponent>();
	ARGUS_RETURN_ON_NULL(WorldCellComponentRef, ArgusECSLog);

}

void UWorldCellComponentData::ReinitializeComponentForEntityPostLoad(ArgusEntity entity) const
{
	WorldCellComponent* WorldCellComponentRef = entity.GetComponent<WorldCellComponent>();
	ARGUS_RETURN_ON_NULL(WorldCellComponentRef, ArgusECSLog);

}

void UWorldCellComponentData::OnComponentDataLoaded() const
{
}

bool UWorldCellComponentData::MatchesType(const UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	return other->IsA<UWorldCellComponentData>();
}
