// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#include "WorldReferenceComponentData.h"
#include "ArgusLogging.h"
#include "ArgusStaticData.h"

void UWorldReferenceComponentData::InstantiateComponentForEntity(ArgusEntity entity) const
{
	WorldReferenceComponent* WorldReferenceComponentRef = entity.GetOrAddComponent<WorldReferenceComponent>();
	ARGUS_RETURN_ON_NULL(WorldReferenceComponentRef, ArgusECSLog);

}

bool UWorldReferenceComponentData::MatchesType(UComponentData* other) const
{
	if (!other)
	{
		return false;
	}

	const UWorldReferenceComponentData* otherComponentData = Cast<UWorldReferenceComponentData>(other);
	if (!otherComponentData)
	{
		return false;
	}

	return true;
}
