// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "SoftPtrLoadStore.h"
#include "ArgusEntity.h"
#include "ArgusEntityTemplate.h"
#include "Engine/Texture.h"

#pragma region UArgusEntityTemplate
	UArgusEntityTemplate* FSoftPtrLoadStore_UArgusEntityTemplate::LoadAndStorePtr() const
	{
		if (m_hardPtr)
		{
			return m_hardPtr.Get();
		}

		m_hardPtr = m_softPtr.LoadSynchronous();
		return m_hardPtr.Get();
	}

	bool FSoftPtrLoadStore_UArgusEntityTemplate::AsyncPreLoadAndStorePtr() const
	{
		if (m_hardPtr)
		{
			return true;
		}

		AssetLoadingComponent* assetLoadingComponent = ArgusEntity::GetSingletonEntity().GetComponent<AssetLoadingComponent>();
		ARGUS_RETURN_ON_NULL_BOOL(assetLoadingComponent, ArgusStaticDataLog);

		assetLoadingComponent->m_streamableManager.RequestAsyncLoad(m_softPtr.ToSoftObjectPath(), FStreamableDelegate::CreateLambda
		(
			[this]()
			{
				m_hardPtr = m_softPtr.Get();
			})
		);

		return true;
	}

	void FSoftPtrLoadStore_UArgusEntityTemplate::SetHardPtr(UArgusEntityTemplate* pointer)
	{
		m_hardPtr = pointer;
	};
#pragma endregion

#pragma region UTexture
	UTexture* FSoftPtrLoadStore_UTexture::LoadAndStorePtr() const
	{
		if (m_hardPtr)
		{
			return m_hardPtr.Get();
		}

		m_hardPtr = m_softPtr.LoadSynchronous();
		return m_hardPtr.Get();
	}

	bool FSoftPtrLoadStore_UTexture::AsyncPreLoadAndStorePtr() const
	{
		if (m_hardPtr)
		{
			return true;
		}

		AssetLoadingComponent* assetLoadingComponent = ArgusEntity::GetSingletonEntity().GetComponent<AssetLoadingComponent>();
		ARGUS_RETURN_ON_NULL_BOOL(assetLoadingComponent, ArgusStaticDataLog);

		assetLoadingComponent->m_streamableManager.RequestAsyncLoad(m_softPtr.ToSoftObjectPath(), FStreamableDelegate::CreateLambda
		(
			[this]()
			{
				m_hardPtr = m_softPtr.Get();
			})
		);

		return true;
	}

	void FSoftPtrLoadStore_UTexture::SetHardPtr(UTexture* pointer)
	{
		m_hardPtr = pointer;
	};
#pragma endregion
