name: Compile All BP

on:
  workflow_dispatch:
  workflow_call:
  
jobs:
  run-commandlet:
    runs-on: self-hosted
    steps:
      - name: Compiling All Blueprints
        shell: powershell
        run: ${{ secrets.PATH_TO_EDITOR_CMD }} "${{ secrets.PATH_TO_UPROJECT }}" -run=CompileAllBlueprints -Unattended -NoLogTimes
