name: Hello World

on:
  workflow_dispatch:

jobs:
  non-unity-job:
    runs-on: self-hosted
    steps:
      - name: Making non-unity build
        shell: powershell
        run: |
             $Process = Start-process -FilePath "C:\Users\treym\GameDevelopment\UnrealEngine\Engine\Build\BatchFiles\RunUBT.bat" -ArgumentList "C:\Users\treym\GameDevelopment\Argus\Argus\Argus.uproject Win64 Development ArgusEditor -DisableAdaptiveUnity -DisableUnity -NoPCH -NoSharedPCH" -NoNewWindow -PassThru
             $Process.WaitForExit()
