name: Hello World

on:
  workflow_dispatch:

permissions: {}

jobs:
  update-runner: 
    uses: ./.github/workflows/UpdateRunner.yml
    secrets: inherit

  hello-world:
    runs-on: self-hosted
    needs: 
      - update-runner
    steps:
      - name: Hello World!
        shell: powershell
        run: echo "Hello World!"
