name: Hello World

on:
  workflow_dispatch:

jobs:
  hello-job:
    runs-on: self-hosted
    steps:
      - name: hello-world
        run: echo "Hello World!"

  goodbye-job:
    runs-on: self-hosted
    needs:
      - hello-job
    steps:
      - name: goodbye-world
        run: echo "Goodbye World!"
  
	
