name: Hello World

on:
  workflow_dispatch:

jobs:
  non-unity-job:
    runs-on: self-hosted
    steps:
      - name: Making non-unity build
        shell: powershell
        run: ${{ secrets.PATH_TO_EDITOR_CMD }} "${{ secrets.PATH_TO_UPROJECT }}" -run=CompileAllBlueprints -Unattended -NoLogTimes
