name: Nightly

on:
   workflow_dispatch:
   schedule:
     - cron: "0 6 * * *"

permissions: {}

jobs:
  update-runner: 
    uses: ./.github/workflows/UpdateRunner.yml
    secrets: inherit

  compile-all-bp:
    needs:
      - update-runner 
    uses: ./.github/workflows/CompileAllBP.yml
    secrets: inherit

  non-unity:
    needs:
      - compile-all-bp
    uses: ./.github/workflows/ValidateNonUnityBuild.yml
    secrets: inherit
             
  packaged-build: 
    needs:
      - non-unity
    uses: ./.github/workflows/MakePackagedBuild.yml
    secrets: inherit

  update-ability-records:
    needs: 
      - packaged-build
    uses: ./.github/workflows/UpdateAbilityRecords.yml
    secrets: inherit
