name: Nightly

on:
   workflow_dispatch:
   schedule:
     - cron: "0 6 * * *"

jobs: 
  build: 
    runs-on: self-hosted
    steps:
      - name: Cook, Stage & Package UE Project
        uses: OrchidIsle/UE5-Build-Project@latest
        with:
          RUNUAT_PATH: ${{ secrets.PATH_TO_RUN_UAT }}
          UPROJECT_PATH: ${{ secrets.PATH_TO_UPROJECT }}
          BUILD_CONFIG: Development
          PLATFORM: Win64
          CLEAN: true
          COOK: true
          STAGE: true
          PACKAGE: true
          ARCHIVE: true
          ARCHIVE_PATH: ${{ secrets.PATH_TO_ARCHIVE_DIR }}
          NULLRHI: true
          EDITOR: true
