name: Update Ability Records

on:
  workflow_dispatch:
  
jobs:
  run-commandlet:
    runs-on: self-hosted
    steps:
      - name: Running UpdateAbilityRecords Commandlet
        shell: powershell
        run: |
          $command = "& `"${{ secrets.PATH_TO_EDITOR_CMD }}`" `"${{ secrets.PATH_TO_UPROJECT }}`" -run=UpdateAbilityRecordsCommandlet -Unattended -NoLogTimes"
          Invoke-Expression $command
  
