// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "CoreMinimal.h"
#include "ComponentDependencies/AbilityComponentStates.h"

class IAbilityComponentObserver
{
public:
};

class AbilityComponentObservers
{
private:
	TArray<IAbilityComponentObserver*> m_AbilityComponentObservers;

public:
	void AddObserver(IAbilityComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_AbilityComponentObservers.Add(observer);
	}

	void RemoveObserver(IAbilityComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_AbilityComponentObservers.RemoveAll
		(
			[observer] (IAbilityComponentObserver* other)
			{
				return other == observer;
			}
		);
	}

private:

	friend struct AbilityComponent;
};
