// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ArgusContainerAllocator.h"
#include "CoreMinimal.h"
#include "ComponentDependencies/TaskComponentStates.h"

class IArgusDecalComponentObserver
{
public:
};

class ArgusDecalComponentObservers
{
private:
	TArray<IArgusDecalComponentObserver*, ArgusContainerAllocator<2u> > m_ArgusDecalComponentObservers;

public:
	void AddObserver(IArgusDecalComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_ArgusDecalComponentObservers.Add(observer);
	}

	void RemoveObserver(IArgusDecalComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_ArgusDecalComponentObservers.RemoveAll
		(
			[observer] (IArgusDecalComponentObserver* other)
			{
				return other == observer;
			}
		);
	}

	void Reset()
	{
		m_ArgusDecalComponentObservers.Reset();
	}

private:

	friend struct ArgusDecalComponent;
};
