// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "CoreMinimal.h"
#include "ComponentDependencies/TaskComponentStates.h"

class IAvoidanceGroupingComponentObserver
{
public:
};

class AvoidanceGroupingComponentObservers
{
private:
	TArray<IAvoidanceGroupingComponentObserver*> m_AvoidanceGroupingComponentObservers;

public:
	void AddObserver(IAvoidanceGroupingComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_AvoidanceGroupingComponentObservers.Add(observer);
	}

	void RemoveObserver(IAvoidanceGroupingComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_AvoidanceGroupingComponentObservers.RemoveAll
		(
			[observer] (IAvoidanceGroupingComponentObserver* other)
			{
				return other == observer;
			}
		);
	}

private:

	friend struct AvoidanceGroupingComponent;
};
