// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "CoreMinimal.h"
#include "ComponentDependencies/TaskComponentStates.h"

class ICarrierComponentObserver
{
public:
};

class CarrierComponentObservers
{
private:
	TArray<ICarrierComponentObserver*> m_CarrierComponentObservers;

public:
	void AddObserver(ICarrierComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_CarrierComponentObservers.Add(observer);
	}

	void RemoveObserver(ICarrierComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_CarrierComponentObservers.RemoveAll
		(
			[observer] (ICarrierComponentObserver* other)
			{
				return other == observer;
			}
		);
	}

private:

	friend struct CarrierComponent;
};
