// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "CoreMinimal.h"
#include "ComponentDependencies/ConstructionComponentStates.h"

class IConstructionComponentObserver
{
public:
};

class ConstructionComponentObservers
{
private:
	TArray<IConstructionComponentObserver*> m_ConstructionComponentObservers;

public:
	void AddObserver(IConstructionComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_ConstructionComponentObservers.Add(observer);
	}

	void RemoveObserver(IConstructionComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_ConstructionComponentObservers.RemoveAll
		(
			[observer] (IConstructionComponentObserver* other)
			{
				return other == observer;
			}
		);
	}

private:

	friend struct ConstructionComponent;
};
