// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ArgusContainerAllocator.h"
#include "CoreMinimal.h"
#include "ComponentDependencies/TaskComponentStates.h"

class IHealthComponentObserver
{
public:
};

class HealthComponentObservers
{
private:
	TArray<IHealthComponentObserver*, ArgusContainerAllocator<2> > m_HealthComponentObservers;

public:
	void AddObserver(IHealthComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_HealthComponentObservers.Add(observer);
	}

	void RemoveObserver(IHealthComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_HealthComponentObservers.RemoveAll
		(
			[observer] (IHealthComponentObserver* other)
			{
				return other == observer;
			}
		);
	}

	void Reset()
	{
		m_HealthComponentObservers.Reset();
	}

private:

	friend struct HealthComponent;
};
