// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ArgusContainerAllocator.h"
#include "CoreMinimal.h"
#include "ComponentDependencies/TaskComponentStates.h"

class IObserversComponentObserver
{
public:
};

class ObserversComponentObservers
{
private:
	TArray<IObserversComponentObserver*, ArgusContainerAllocator<2> > m_ObserversComponentObservers;

public:
	void AddObserver(IObserversComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_ObserversComponentObservers.Add(observer);
	}

	void RemoveObserver(IObserversComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_ObserversComponentObservers.RemoveAll
		(
			[observer] (IObserversComponentObserver* other)
			{
				return other == observer;
			}
		);
	}

private:

	friend struct ObserversComponent;
};
