// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "CoreMinimal.h"
#include "ComponentDependencies/PassengerComponentStates.h"

class IPassengerComponentObserver
{
public:
};

class PassengerComponentObservers
{
private:
	TArray<IPassengerComponentObserver*> m_PassengerComponentObservers;

public:
	void AddObserver(IPassengerComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_PassengerComponentObservers.Add(observer);
	}

	void RemoveObserver(IPassengerComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_PassengerComponentObservers.RemoveAll
		(
			[observer] (IPassengerComponentObserver* other)
			{
				return other == observer;
			}
		);
	}

private:

	friend struct PassengerComponent;
};
