// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ArgusContainerAllocator.h"
#include "CoreMinimal.h"
#include "ComponentDependencies/TaskComponentStates.h"

class IResourceComponentObserver
{
public:
};

class ResourceComponentObservers
{
private:
	TArray<IResourceComponentObserver*, ArgusContainerAllocator<2u> > m_ResourceComponentObservers;

public:
	void AddObserver(IResourceComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_ResourceComponentObservers.Add(observer);
	}

	void RemoveObserver(IResourceComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_ResourceComponentObservers.RemoveAll
		(
			[observer] (IResourceComponentObserver* other)
			{
				return other == observer;
			}
		);
	}

	void Reset()
	{
		m_ResourceComponentObservers.Reset();
	}

private:

	friend struct ResourceComponent;
};
