// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ArgusContainerAllocator.h"
#include "CoreMinimal.h"
#include "ComponentDependencies/ResourceSet.h"
#include "ComponentDependencies/TaskComponentStates.h"

class IResourceComponentObserver
{
public:
	virtual void OnChanged_m_currentResources(const FResourceSet& oldValue, const FResourceSet& newValue) = 0;
};

class ResourceComponentObservers
{
private:
	TArray<IResourceComponentObserver*, ArgusContainerAllocator<2u> > m_ResourceComponentObservers;

public:
	void AddObserver(IResourceComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_ResourceComponentObservers.Add(observer);
	}

	void RemoveObserver(IResourceComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_ResourceComponentObservers.RemoveAll
		(
			[observer] (IResourceComponentObserver* other)
			{
				return other == observer;
			}
		);
	}

	void Reset()
	{
		m_ResourceComponentObservers.Reset();
	}

private:
	void OnChanged_m_currentResources(const FResourceSet& oldValue, const FResourceSet& newValue)
	{
		for (int32 i = 0; i < m_ResourceComponentObservers.Num(); ++i)
		{
			m_ResourceComponentObservers[i]->OnChanged_m_currentResources(oldValue, newValue);
		}
	};

	friend struct ResourceComponent;
};
