// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ArgusContainerAllocator.h"
#include "CoreMinimal.h"
#include "ComponentDependencies/TaskComponentStates.h"

class ISpawningComponentObserver
{
public:
};

class SpawningComponentObservers
{
private:
	TArray<ISpawningComponentObserver*, ArgusContainerAllocator<2> > m_SpawningComponentObservers;

public:
	void AddObserver(ISpawningComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_SpawningComponentObservers.Add(observer);
	}

	void RemoveObserver(ISpawningComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_SpawningComponentObservers.RemoveAll
		(
			[observer] (ISpawningComponentObserver* other)
			{
				return other == observer;
			}
		);
	}

	void Reset()
	{
		m_SpawningComponentObservers.Reset();
	}

private:

	friend struct SpawningComponent;
};
