// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "CoreMinimal.h"
#include "ComponentDependencies/TaskComponentStates.h"

class ITimerComponentObserver
{
public:
};

class TimerComponentObservers
{
private:
	TArray<ITimerComponentObserver*> m_TimerComponentObservers;

public:
	void AddObserver(ITimerComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_TimerComponentObservers.Add(observer);
	}

	void RemoveObserver(ITimerComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_TimerComponentObservers.RemoveAll
		(
			[observer] (ITimerComponentObserver* other)
			{
				return other == observer;
			}
		);
	}

private:

	friend struct TimerComponent;
};
