// Copyright Karazaa. This is a part of an RTS project called Argus.
// AUTOGENERATED FILE

#pragma once

#include "ArgusContainerAllocator.h"
#include "CoreMinimal.h"
#include "ComponentDependencies/TaskComponentStates.h"

class ITransformComponentObserver
{
public:
};

class TransformComponentObservers
{
private:
	TArray<ITransformComponentObserver*, ArgusContainerAllocator<2> > m_TransformComponentObservers;

public:
	void AddObserver(ITransformComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_TransformComponentObservers.Add(observer);
	}

	void RemoveObserver(ITransformComponentObserver* observer)
	{
		if (!observer)
		{
			return;
		}

		m_TransformComponentObservers.RemoveAll
		(
			[observer] (ITransformComponentObserver* other)
			{
				return other == observer;
			}
		);
	}

private:

	friend struct TransformComponent;
};
